### ISSUE TITLE
Error: Could not find or load main class AppClass

### ISSUE THREAD

**Issue by Borja123** [leaningtech/cheerpj-meta#10]
I managed to create the file my_aplication. jar. js, in my case it is called GP-Multiplexer-master. jar. js.

Then I have created a simple server with python to serve it, but when I try to view the content I get an error. The error is as follows:"Error: Could not find or load main class AppClass".

My python server code is as follows:

`
from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer
import SocketServer

class S(BaseHTTPRequestHandler):
    def _set_headers(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()

    def do_GET(self):
        self._set_headers()
        self.wfile.write("<!DOCTYPE html><html><head><meta  charset = \"utf-8\" ><title > CheerpJ test </title ><script  src = \" https://cjrtnc.leaningtech.com/loader.js \" > </script></head><body><script>cheerpjInit (); cheerpjCreateDisplay ( 800 , 600 );console.log(\"PASA\");cheerpjRunMain(\"AppClass\", \"/app/GP-Multiplexer-master.jar\");</script> </body></html>")

    def do_HEAD(self):
        self._set_headers()
        
    def do_POST(self):
        # Doesn't do anything with posted data
        self._set_headers()
        self.wfile.write("<html><body><h1>POST!</h1></body></html>")
        
def run(server_class=HTTPServer, handler_class=S, port=80):
    server_address = ('', port)
    httpd = server_class(server_address, handler_class)
    print 'Starting httpd...'
    httpd.serve_forever()

if __name__ == "__main__":
    from sys import argv

    if len(argv) == 2:
        run(port=int(argv[1]))
    else:
        run()
`
I do the following to pass you the jar list: cheerpjRunMain ("AppClass","/app/GP-GP-Multiplexer-master.jar")

I was wondering if you could point me out where I'm making the mistake.

Greetings,

**Comment by alexp-sssup** [comment]
Can you check using the network tab of the browser developer tools if the GP-GP-Multiplexer-master.jar is actually loaded?

**Comment by Borja123** [comment]
I don't think it's loaded my *. jar attached img.

![image](https://user-images.githubusercontent.com/26282371/33272314-037e141e-d38a-11e7-8a2f-6990b9447df5.png)

I have created an app/ folder and put the *. jar file inside it. Then refer to it in the htlm with :
 cheerpjRunMain(\"AppClass\", \"/app/GP-Multiplexer-master.jar\");

**Comment by alexp-sssup** [comment]
Both the .jar and .jar.js files should be in the root of the web server, and _not_ in the /app/ sub-directory. ```/app/``` is a virtual _mount point_ that refers to the root of the HTTP server.

**Comment by Borja123** [comment]
I can't make it work.

In my root directory I have the. jar and. jar. js files

![image](https://user-images.githubusercontent.com/26282371/33273714-6e2fcbd2-d38e-11e7-8d4f-e92d1bb15836.png)

In my file my_web_server. py I invoke the function cheerpjRunMain () as follows:

`cheerpjRunMain("AppClass", "GP-Multiplexer-master.jar");`

But I can't get the. jar file to load

**Comment by alexp-sssup** [comment]
````
cheerpjRunMain("AppClass", "/app/GP-Multiplexer-master.jar");
```

On the CheerpJ side you need to use ````/app```, otherwise the system won't be able to know that the JAR is on the HTTP server. If you are familiar with Unix-like system, CheerpJ has multiple mount points, such as:

```
/app/ -> the root of the HTTP server
/files/ -> a persistent IndexedDB based file storage
/lt/ -> the Java runtime hosted by LeaningTech
```

**Comment by Borja123** [comment]
Sorry for my ignorance but I'm not able to make it work. I'm gonna try to explain myself one last time.

I have an application in Java with a main class that contains the `public static void main (String[] args) {...` (This application does not have a graphical interface, it is an application that gives a result per console).

I managed to generate the. jar. js file with the python script cheerpjfy.

Leaving in the root directory the. jar and jar. js files I have created another one with a simple python server.

When I launch my server and try to load the web I get the following error: `"Error: Could not find or load main class main".`

The problem is that I don't load the *. jar file and I think it's because I don't understand how the cheerpjRunMain () function works. I understand that this function has two input parameters:

- first parameter, AppClass (in the Getting Started example) I think that parameter is the name of the class of the java project where the public static void main function is located. 

- A second parameter that indicates what your *. jar file is called, in my case there are no dependencies.

as I understand it my function cheerpjRunMain () would look like this: cheerpjRunMain `("main","/app/GP-GP-Multiplexer-master.jar")`

I can't get it to work and I don't understand why, if you could point me in the wrong direction, I would be very grateful.

Again apologize for my ignorance.

**Comment by alexp-sssup** [comment]
@Borja123 I wonder if you are making a simple typo error. In your last message you wrote:

```
cheerpjRunMain ("main","/app/GP-GP-Multiplexer-master.jar")
```

But in the screenshot above the file name is only ```GP-Multiplexer-master.jar```. Please note ```GP``` vs ```GP-GP```. Please try with the exact following command.

```
cheerpjRunMain("AppClass", "/app/GP-Multiplexer-master.jar");
```

With the browser debugging tools you can see what files are loaded over the network. If you see a 404 error on your local server it means that it is loading the wrong file.

**Comment by Borja123** [comment]
The mistake you mention to me is a mistake I made in writing the previous post.

In using the chrome debugger in the console I get the following error:

![image](https://user-images.githubusercontent.com/26282371/33312544-7f3d4f86-d428-11e7-9fe0-59e8b2b50011.png)

**Comment by alexp-sssup** [comment]
Are you sure your custom web server is behaving properly? What happens if you visit the following url?

```http://localhost/GP-Multiplexer-master.jar```

**Comment by Borja123** [comment]
I get the following problem:

![image](https://user-images.githubusercontent.com/26282371/33313054-f22cd97a-d429-11e7-908a-f94509fc22e9.png)

I think the problem has to be my python server doesn't work properly. I'll look for a new example server in python and try again.
If I find the code of a properly functioning server I will upload it so that if someone else has this problem I can use it as an example.

A greeting, thank you very much for your help and pardon for the inconvenience.

**Comment by alexp-sssup** [comment]
Python includes a fully working web server already, use that.

For python2
```
python -m SimpleHTTPServer 80
```

For python3
```
python3 -m http.server 80
```

**Comment by Borja123** [comment]
He keeps giving me a mistake.

I in the console I place myself inside the folder that has my project and launch the server as you tell me.

`python3 -m http.server 80`

When I enter my browser in the address: http://0.0.0.0:80/ I get the following error.

![image](https://user-images.githubusercontent.com/26282371/33314548-48d96352-d42e-11e7-82e4-1ecad4e17e66.png)

But if I try to access http://localhost:80/ I get a different bug.

![image](https://user-images.githubusercontent.com/26282371/33315032-c4f52826-d42f-11e7-95fb-d84a54bb19e2.png)

When I inspect the browser debugger, the *. jar file does not appear in the source tab. I think it's still unloaded.

![image](https://user-images.githubusercontent.com/26282371/33315138-171b70b0-d430-11e7-9c53-ccb07941a68e.png)

but If I try to access http://0.0.0.0:80/GP-Multiplexer-master.jar the browser starts a download of the file GP-Multiplexer-master.jar

My index. html is copied from the gettting started example, with the cheerpjRunMain () function changing as you indicated.

**Comment by alexp-sssup** [comment]
Please attach the HTML file you are using and the JAR file. The JAR.JS file is not required.

**Comment by Borja123** [comment]
Attached are the compressed files:

[Archivo comprimido.zip](https://github.com/leaningtech/cheerpj-meta/files/1509614/Archivo.comprimido.zip)

**Comment by alexp-sssup** [comment]
Your main class is not called ```AppClass```, but ```main```.

```
cheerpjRunMain("main", "/app/GP-Multiplexer-master.jar");
```

**Comment by Borja123** [comment]
You're right about that.

Thank you so much for helping me, sorry for my clumsiness and again thank you very much.
