### ISSUE TITLE
Reflective call of native unexpectedly throws exception

### ISSUE THREAD

**Issue by jburse** [leaningtech/cheerpj-meta#102]
Dear Leaning Technologies,

After a 24 month pause after testing CheerpJ 1.3, I am now
conducting some experiments again with CheerpJ 2.1.
How is reflection supposed to work with native methods?

Its a greate joy working with CheerpJ and the JDK 1.8
support, since I promoted my own code also to JDK 1.8.
I am hacking around some Console access via this reflection:
```
        try {
            Class<?> clazz = Class.forName("java.io.Console");
            encoding = clazz.getDeclaredMethod("encoding");
            encoding.setAccessible(true);
        } catch (ClassNotFoundException e) {
            encoding = null;
        } catch (NoSuchMethodException e) {
            encoding = null;
        } catch (Throwable e) {
            e.printStackTrace();
            encoding = null;
        }
```
If encoding is found it is later invoked:
```
        System.err.println("encoding="+encoding);
        if (encoding != null) {
            String csname;
            try {
                csname = (String) encoding.invoke(null);
            } catch (IllegalAccessException e) {
                csname = null;
            } catch (InvocationTargetException e) {
                csname = null;
            } catch (Throwable e) {
                e.printStackTrace();
                csname = null;
            }
```
From the console log of CheerpJ, it seems that encoding
is found. But invoking it gives an internal Assertion violation
and then something Uncaught.

**Comment by jburse** [comment]
The internal assertion goes into the debugger:

![image](https://user-images.githubusercontent.com/5411487/94162190-bdb43c80-fe86-11ea-8992-56b6efd405fa.png)

And when continuing the debugger I see this:

![image](https://user-images.githubusercontent.com/5411487/94162508-14217b00-fe87-11ea-9016-57d95794d5be.png)

I am expecting something else than NullPointerException, since it
is a static method. But knowing that this is the outcome for CheerpJ
I could adapt my Java code correspondingly. But not sure whether

this is a bug or feature?

Bye

**Comment by alexp-sssup** [comment]
Hi,

thanks for your bug report. Unfortunately we are extremely busy at the minute supporting commercial customers, and will not be able to look at this in the short term. 

We will keep this bug report open, and will have a look at it when possible.  Unfortunately, I can’t give you a timeline on when that will be.

If this is for a commercial application, or if you are looking to get an Essential licence for CheerpJ, please get in touch with info@leaningtech.com, as we will be able to prioritize this again for you.

**Comment by jburse** [comment]
Nope, I only wanted to make a ticket from using your community 
edition for the purpose of technical evaluation:

**Comment by jburse** [comment]
Whats the goal of a community edition and GitHub with issue functionality,
when you are not sure whether you want or do not want bug reports?

**Comment by alexp-sssup** [comment]
This issue is fixed with endpoint: https://cjrtnc.leaningtech.com/20201027/loader.js

Please note that Console.encoding() is not very useful anyway, since it returns "null" on Linux native and CheerpJ now returns null as well. The crash is nevertheless fixed.

**Comment by jburse** [comment]
Interesting, thanks!
