### ISSUE TITLE
Failed to open CheerpJ Global Bug Report 

### ISSUE THREAD

**Issue by oeway** [leaningtech/cheerpj-meta#104]
Hi, sometimes I see cheerpj loader try to open a google docs window but failed due to CORS error, see below:
```
Access to XMLHttpRequest at 'https://docs.google.com/forms/d/e/1FAIpQLScErDRKZvSy1JAdiRSZfAsjf711VWdSdkczuSYHfIHQbtyFXA/formResponse' from origin 'https://ij.imjoy.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
loader.js:3069 POST https://docs.google.com/forms/d/e/1FAIpQLScErDRKZvSy1JAdiRSZfAsjf711VWdSdkczuSYHfIHQbtyFXA/formResponse net::ERR_FAILED
cjReportError @ loader.js:3069
(anonymous) @ loader.js:831
error (async)
cheerpjInitOnce @ loader.js:820
cheerpjInit @ loader.js:2016
(anonymous) @ index.js:231
(anonymous) @ index.js:888
```

**Comment by alexp-sssup** [comment]
This is not a real error, but just a side effect of our automatic bug report system. Something else is making your application crash before that.

This is documented here: https://github.com/leaningtech/cheerpj-meta/wiki/Frequently-Asked-Questions#my-application-compiled-with-cheerpj-does-not-work-and-i-see-a-cross-origin-error-to-a-google-service-in-the-console-whats-going-on

You can disable this telemetry if you wish: https://github.com/leaningtech/cheerpj-meta/wiki/Runtime-API#disableerrorreporting
