### ISSUE TITLE
App crashes with error "no such method: sun.awt.image.ImageWatched..."

### ISSUE THREAD

**Issue by oeway** [leaningtech/cheerpj-meta#106]
I see this error from time to time, and it cause the entire app to crash:
```
Uncaught (in promise) no such method: sun.awt.image.ImageWatched$WeakLink.lambda$update$0(ImageObserver,Image,int,int,int,int,int)Boolean/invokeStatic
```

and error points to line 2268 of the loader.js file (version: 20200927): 
```js
			currentThread.parent.endPromise.fail(detailMessage);
```

To reproduce the issue:
1. goto  https://ij.imjoy.io/
2. click "File -> New -> Image...", then click ok in the dialog
3. now click "File -> Save", then the app crashes and you can see the error in the console.

**Comment by alexp-sssup** [comment]
We expect this problem to be fixed with the new CheerpJ 3.0 architecture. Please let us know if that is not the case.
