### ISSUE TITLE
Failed to read image with awt.Toolkit

### ISSUE THREAD

**Issue by oeway** [leaningtech/cheerpj-meta#107]
If I mount a jpeg image into the file system and read with `Image img = Toolkit.getDefaultToolkit().createImage(file_path)`, it returns null.

[This](https://github.com/imagej/ImageJA/blob/e3c54c68c1d4344412dcf23c8b9f50f34e5c3b9a/src/main/java/ij/io/Opener.java#L635-L654) is it being used in my project which currently failed and I had to switch to ImageIO.

(I tried to create a minimal test case, but not sure how to mount a file to https://javafiddle.leaningtech.com/)

**Comment by alexp-sssup** [comment]
This issue might be fixed with endpoint: https://cjrtnc.leaningtech.com/20201008/loader.js

We can't be sure without a full test case, if the problem is still there please provide one.

**Comment by oeway** [comment]
@alexp-sssup It works, thanks!
