### ISSUE TITLE
Support loading precompiled jar from IndexedDB

### ISSUE THREAD

**Issue by oeway** [leaningtech/cheerpj-meta#109]
Currently, it seem cheerpj can only load compiled .jar.js file from http backed mounting points, it will be super helpful if we can load .jar.js directly from IndexedDB (`/files`). This is crucial since in my case, the compiled file is >500MB, it takes a long time to load.

**Comment by alexp-sssup** [comment]
With the new CheerpJ 3.0 architecture precompiled jar.js files are not required anymore. I am closing this feature request since it is now obsolete.
