### ISSUE TITLE
Typos in code samples in documentation

### ISSUE THREAD

**Issue by ComFreek** [leaningtech/cheerpj-meta#111]
In https://github.com/leaningtech/cheerpj-meta/wiki/Runtime-API:

- "cheerpjRunJarWithClassPath" should be "cheerpjRunJarWithClasspath" (with lower-case "path")
- "cherpjRunMain" should be "cheerpjRunMain"

I confirmed these names changes with the source https://cjrtnc.leaningtech.com/2.1/loader.js.

**Comment by alexp-sssup** [comment]
Thanks for reporting this. The typos have been fixed.
