### ISSUE TITLE
HTTP handler seems not to return EOF / Seamonkey browser specific?

### ISSUE THREAD

**Issue by jburse** [leaningtech/cheerpj-meta#113]
This is a follow-up to this issue. I don't know how to re-open the issue,
maybe what I am reporting is only a sub-defect:

**Feature request support originating HTTP URLs #112**
https://\github.com/leaningtech/cheerpj-meta/issues/112

We have now the impression that URLConnection returns 
indeed a stream, but this stream is not 100% compatible
with Java. Especially Content-Length seems possibly

not correctly handled. I am using on the server side Tomcat.
My own code reads a text file, until EOF. By a standard loop
that uses BufferedReader.readLine(). The loop stops

when BufferedReader.readLine() returns null. Everything
seems to work fine with the Java runtime:

![image](https://user-images.githubusercontent.com/5411487/97730010-94b14800-1ad3-11eb-911b-965f63853f5f.png)

**Comment by jburse** [comment]
When I use CheerpJ runtime the test hangs. The progress
bar is part of my test application to show that the application
is busy. So I see this in the browser:

![Unbenannt](https://user-images.githubusercontent.com/5411487/97730396-173a0780-1ad4-11eb-8c53-9d9c5eee7b74.PNG)

The problem could be a thread yield problem, or the
problem could be that I am using HTTP 1.1 and not
HTTP 1.0. At least the CheerpJ URLConnection has 

requested keep alive:

![Unbenannt3](https://user-images.githubusercontent.com/5411487/97730535-48b2d300-1ad4-11eb-97ed-1a84384fd9e2.PNG)

And the server has already delivered the text to the client:



I am suspecting the the EOF is missing. The same problem doesn't
happen when I use CheerpJ with /app and the virtual file system.
So I guess its not a problem of my client, rather 

![Unbenannt4](https://user-images.githubusercontent.com/5411487/97730798-9c252100-1ad4-11eb-90ed-793d577c32e6.PNG)

of the protocol implementation for URLConnection. Should I
switch off keep-alive? How do I do this in a compatible
way with CheerpJ?

**Comment by jburse** [comment]
Seems to be a browser problem, i.e. problem with Seamonkey. 
In Chrome it wurks:

![Unbenannt7](https://user-images.githubusercontent.com/5411487/97732545-f58e4f80-1ad6-11eb-876b-864ebcf91079.PNG)

Woa! Thats great. But how can I make it work for Seamonkey?
Chrome seems to send a little bit more HTTP parameters during GET:

![Unbenannt8](https://user-images.githubusercontent.com/5411487/97732680-29697500-1ad7-11eb-8bb2-78b57202dc1f.PNG)

**Comment by jburse** [comment]
Seems to be a very specific Seamonkey problem. For example Firefox,
also from Mozilla, works fine:

**Comment by marsicplusplus** [comment]
Hi @jburse, CheerpJ is being tested and used on other major browsers like Firefox or Chrome and unfortunately Seamonkey is not one we are planning to target and/or to support.

Because of that we don't know enough about it to be able to help you.

Thanks for your understanding,

Lorenzo
