### ISSUE TITLE
build dacapo-9.12-MR1-bach.jar failed

### ISSUE THREAD

**Issue by Wandshuai** [leaningtech/cheerpj-meta#115]
hi，
  i want test the performance of the converted js ，and i try to use dacapo to test，but cheepj conver it failed。

dacapo download from here :http://dacapobench.org/

anyway，
  how can i pass parameter to the jar file in the html
![image](https://user-images.githubusercontent.com/37127889/98219316-ce78c780-1f87-11eb-9021-d13c14dad743.png)

**Comment by alexp-sssup** [comment]
The use of ```cheerpjRunJar``` is documented here: https://github.com/leaningtech/cheerpj-meta/wiki/Runtime-API#running-applications-and-jars

The arguments must be passed as separate strings, in your screenshot I can see you passed just 1 string, which is interpreted a the name of a jar.
