### ISSUE TITLE
awt menu goes out of the screen

### ISSUE THREAD

**Issue by oeway** [leaningtech/cheerpj-meta#116]
Hi, the awt menu (both menu and popup menu) can go out of the screen in both vertically and horizontally (see [the issue here](https://github.com/imjoy-team/imagej.js/issues/33)). A correct implementation should be:
 1. allow scrolling when the menu is too long
 2. when toughing the left or right border, keep the entire menu within the screen.

I tried to apply some css to fix it but couldn't get it to work, it might be easier to handle these issues directly from cheerpj.

**Comment by alexp-sssup** [comment]
Endpoint https://cjrtnc.leaningtech.com/20201217/loader.js now has a mechanisms to reposition the popup windows to keep them in the screen. Scrolling to support displays which are too small for the popups is not something that native Java supports, so it falls outside of the scope of CheerpJ.
