### ISSUE TITLE
cheerpJ

### ISSUE THREAD

**Issue by Abhishekjmt** [leaningtech/cheerpj-meta#117]
I WANT TO USE JAVA IN CHROME . I HAVE INSTALLED CHEERPJ EXTENSION IN CHROME . DONE ALL THE PROCEDURE AS GUIDED AT
https://www.lifewire.com/how-to-enable-java-in-chrome-4770854.

I AM USING IT ON www.epfindia.gov.in site . but PDF SIGNER SCREEN IS OPENING BUT NO DIGITAL SIGNATURE IS SHOWN . HOW TO DIGITALLY SIGN PDF IF NO DIGITAL SIGNATURE IS SHOWING . SCREEN SHOT ATTACHED 
![cheerpj issue screen shot](https://user-images.githubusercontent.com/74759723/99769527-78318a00-2b2c-11eb-9b2d-f8e8636a8c37.png)

**Comment by alexp-sssup** [comment]
It appears that this applet tries to access certificate files on your system. This is something which is not allowed by modern browsers for obvious security reasons.

To support advanced authentication, such as smart cards/tokens/certificates, we would need to do some amount of custom work with the Website developer or integrator. This is something that can be made to work, but not something that can work our-of-the-box with the free CheerpJ Applet Runner extension.

**Comment by Abhishekjmt** [comment]
WHAT SHOULD I DO SO THAT IT CAN WORK

On 11/20/20, Alessandro Pignotti <notifications@github.com> wrote:
> It appears that this applet tries to access certificate files on your
> system. This is something which is not allowed by modern browsers for
> obvious security reasons.
>
> To support advanced authentication, such as smart cards/tokens/certificates,
> we would need to do some amount of custom work with the Website developer or
> integrator. This is something that can be made to work, but not something
> that can work our-of-the-box with the free CheerpJ Applet Runner extension.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/leaningtech/cheerpj-meta/issues/117#issuecomment-731050817


-- 
THANKS & REGARDS
ABHISHEK
