### ISSUE TITLE
Unexpected cjResolveNew behaviour

### ISSUE THREAD

**Issue by chubei** [leaningtech/cheerpj-meta#118]
I created a simple Java class:
```code
class Test {
  public Test(double d1) {
    System.out.println(d1);
  }
}
```

I bundled it with `Main.java` with an empty `main` method and created `Main.jar`.

In my html, I loaded CheerpJ from `https://cjrtnc.leaningtech.com/2.1/loader.js` and ran `Main.jar`.

Then in the console , I ran the following code:
```code
cjNew("Test", 1.0)
```

`1.0` got printed as expected.

But when I did:
```code
(await cjResolveNew("Test", ["double"]))(1.0)
```

`0.0` got printed.

What am I doing wrong?

**Comment by alexp-sssup** [comment]
This issue should be fixed with endpoint https://cjrtnc.leaningtech.com/20201231/loader.js

**Comment by chubei** [comment]
That solves the problem. Thanks.
