### ISSUE TITLE
Which libraries and OS are required to use CheerpJ under Ubuntu?

### ISSUE THREAD

**Issue by henrycrutcher** [leaningtech/cheerpj-meta#12]
When I compile my jar I get losts of error messages (below).  It feels like I need to install something, but I'm not sure what it is.  I'm running ubuntu 14.04.01.
XX_3.4.21' not found (required by /tmp/cheerpj_preview/bin/cheerpj)

compiling com/jidesoft/swing/JideSwingUtilities$TraceDebugBorder.class ...
Failure compiling com/jidesoft/swing/JideSwingUtilities$TraceDebugBorder.class
command: /tmp/cheerpj_preview/bin/cheerpj "" -llvm -llvm-exceptions -cp /tmp/tmpf35mcke1/rt.jar.dir/ com/jidesoft/swing/JideSwingUtilities$TraceDebugBorder.class
/tmp/cheerpj_preview/bin/cheerpj: /lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/cheerpj_preview/bin/cheerpj)

compiling com/jidesoft/swing/JideSwingUtilities$viewportSynchronizationChangeListener.class ...
Failure compiling com/jidesoft/swing/JideSwingUtilities$viewportSynchronizationChangeListener.class
command: /tmp/cheerpj_preview/bin/cheerpj "" -llvm -llvm-exceptions -cp /tmp/tmpf35mcke1/rt.jar.dir/ com/jidesoft/swing/JideSwingUtilities$viewportSynchronizationChangeListener.class
/tmp/cheerpj_preview/bin/cheerpj: /lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/cheerpj_preview/bin/cheerpj)

compiling com/jidesoft/swing/JideSwingUtilities.class ...
Failure compiling com/jidesoft/swing/JideSwingUtilities.class
command: /tmp/cheerpj_preview/bin/cheerpj "" -llvm -llvm-exceptions -cp /tmp/tmpf35mcke1/rt.jar.dir/ com/jidesoft/swing/JideSwingUtilities.class
/tmp/cheerpj_preview/bin/cheerpj: /lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/cheerpj_preview/bin/cheerpj)

compiling com/jidesoft/swing/JideTabbedPane$1.class ...
Failure compiling com/jidesoft/swing/JideTabbedPane$1.class
command: /tmp/cheerpj_preview/bin/cheerpj "" -llvm -llvm-exceptions -cp /tmp/tmpf35mcke1/rt.jar.dir/ com/jidesoft/swing/JideTabbedPane$1.class
/tmp/cheerpj_preview/bin/cheerpj: /lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/cheerpj_preview/bin/cheerpj)

compiling com/jidesoft/swing/JideTabbedPane$2.class ...
Failure compiling com/jidesoft/swing/JideTabbedPane$2.class
command: /tmp/cheerpj_preview/bin/cheerpj "" -llvm -llvm-exceptions -cp /tmp/tmpf35mcke1/rt.jar.dir/ com/jidesoft/swing/JideTabbedPane$2.class
/tmp/cheerpj_preview/bin/cheerpj: /lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/cheerpj_preview/bin/cheerpj)

compiling com/jidesoft/swing/JideTabbedPane$3.class ...
Failure compiling com/jidesoft/swing/JideTabbedPane$3.class
command: /tmp/cheerpj_preview/bin/cheerpj "" -llvm -llvm-exceptions -cp /tmp/tmpf35mcke1/rt.jar.dir/ com/jidesoft/swing/JideTabbedPane$3.class
/tmp/cheerpj_preview/bin/cheerpj: /lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/cheerpj_preview/bin/cheerpj)

compiling com/jidesoft/swing/JideTabbedPane$4.class ...
Failure compiling com/jidesoft/swing/JideTabbedPane$4.class
command: /tmp/cheerpj_preview/bin/cheerpj "" -llvm -llvm-exceptions -cp /tmp/tmpf35mcke1/rt.jar.dir/ com/jidesoft/swing/JideTabbedPane$4.class
/tmp/cheerpj_preview/bin/cheerpj: /lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/cheerpj_preview/bin/cheerpj)

compiling com/jidesoft/swing/JideTabbedPane$5.class ...
Failure compiling com/jidesoft/swing/JideTabbedPane$5.class
command: /tmp/cheerpj_preview/bin/cheerpj "" -llvm -llvm-exceptions -cp /tmp/tmpf35mcke1/rt.jar.dir/ com/jidesoft/swing/JideTabbedPane$5.class
/tmp/cheerpj_preview/bin/cheerpj: /lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/cheerpj_preview/bin/cheerpj)

compiling com/jidesoft/swing/JideTabbedPane$6$1.class ...
^CFailure compiling com/jidesoft/swing/JideTabbedPane$6$1.class
command: /tmp/cheerpj_preview/bin/cheerpj "" -llvm -llvm-exceptions -cp /tmp/tmpf35mcke1/rt.jar.dir/ com/jidesoft/swing/JideTabbedPane$6$1.class
/tmp/cheerpj_preview/bin/cheerpj: /lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/cheerpj_preview/bin/cheerpj)
/tmp/cheerpj_preview/bin/cheerpj: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/cheerpj_preview/bin/cheerpj)

**Comment by alexp-sssup** [comment]
To avoid these problems, from CheerpJ 1.1 onwards we will ship a binary build for Linux. Closing.
