### ISSUE TITLE
Opcode_c8 is not defined

### ISSUE THREAD

**Issue by Brilliand** [leaningtech/cheerpj-meta#120]
I'm getting the error message "Opcode_c8 is not defined" while running the very old game "Silent Frontier", which was apparently made for Java 2. You can find the game here: http://web.archive.org/web/20010515021250/http://www.randomthoughts.net/games/sf/

The game is able to load once copied to a local webserver, but gets the aforementioned error while attempting to start the campaign from the beginning.  I've managed to get the game to work locally by decompiling through JAD, fixing the compilation errors, then running it in an old version of Eclipse, but even my recompiled version gets the Opcode_c8 error in the same place when running it through CheerpJ.

**Comment by alexp-sssup** [comment]
Thanks for reporting this. We are currently extremely busy and won't be able to get this fixed immediately. We will let you know when the problem is solved.
