### ISSUE TITLE
Class not being found

### ISSUE THREAD

**Issue by ii-Python** [leaningtech/cheerpj-meta#125]
I'm not a java developer, although I'm having an issue trying to load a pretty simple jar file.
No matter what class I pass into the `cheerpjRunMain()`, it always gives me the "Error: could not find or load class"

I checked that the server is working and sending the JAR file, which it is.
Just to be sure, I checked what classes were inside of the jar file, via `jar vf jarfile.jar`, which gave me `minicraft/core/Game.class` (what I think the main class is).

I tried the full path ^, without the .class, just Game.class, and Game.
None of which work.

Any ideas?

**Comment by marsicplusplus** [comment]
Hi @ii-Python,

You should use 

`cheerpjRunJar("/app/minicraft.jar");`

To run the jar file. But minicraft won´t work in any case, as it seems to be using a custom socket implementation when the jar file is being loaded, not currently supported in CheerpJ.
