### ISSUE TITLE
Could not find main class

### ISSUE THREAD

**Issue by wyskoj** [leaningtech/cheerpj-meta#129]
I'm attempting to run [a program I'm developing](https://midis2jam2.xyz) in the browser with Cheerpj. I compiled the Jar to js locally with the python helper script and uploaded them to my website. Running results in `Error: Could not find or load main class org.wysko.midis2jam2.GuiLauncher` Here is the link to my [test page](https://wysko.org/test.html) where you can see the same error in the console.

I then tried another—smaller—program of mine, which has the same "could not find class" error. So I tried creating a class in the root and calling the true main class nested in a package. This got me a little further, but hit an error. [Here's that log](https://github.com/leaningtech/cheerpj-meta/files/6757559/wysko.org-1625271792757.log). And [here's the test page for that.](https://wysko.org/test2.html)

So I have no idea what's happening since the stack trace is not helpful. Any apparent solutions? I can provide the sources if that helps.

**Comment by marsicplusplus** [comment]
Dear @wyskoj 

From the GitHub page of your project I see that it requires _at least_  Java 15.

Currently, CheerpJ supports up to Java8, therefore the application won't run.

On top of that I see that you are using GLFW to obtain an OpenGL context. To be able to do that some custom JNI methods are required that are not currently implemented in our product.

If you are interested in a custom solution for your application you should contact us at info@leaningtech.com for a more detailed analysis on how to get our solution working with your product.

Best,
Lorenzo
