### ISSUE TITLE
getting started help 

### ISSUE THREAD

**Issue by scottschaffer** [leaningtech/cheerpj-meta#13]
I created the file.jar.js, and I'm trying to follow the simple the Getting Started instructions for the Basic HTML. I'm at the line: cheerpjRunMain("AppClass", "/app/my_application_archive.jar:/app/my_dependency_archive.jar");  
but I don't think I implemented the 'AppClass' correctly or the second parameter.  I only have 1  .jar file. 
Do I use the .class from my app? or use 'AppClass'. What about for the second parameter. Do I use the .jar or the .jar.js? If not, when do I call the .jar.js file?

**Comment by reportmill** [comment]
The parameters are very similar to running java from the command line. So if you ran your app from the command line like this:

	prompt> java -cp my_application_archive.jar:my_dependency_archive.jar my_pkg.MyClass

You would call cheerpjRunMain like this:

	cheerpjRunMain(“my_pkg.MyClass”, "my_application_archive.jar:my_dependency_archive.jar”);

CheerpJ will find and use the .jar.js files automatically. Check in your browser console to make sure all the files are being found. You should only need to use the /app prefix if your jar.js files aren’t in the same directory as your html file and you are referencing them by absolute path.

jeff

**Comment by scottschaffer** [comment]
thanks for the quick reply. Im still pretty new to this, so please excuse my ignorance. You keep referencing 2 .jar files (my_application_archive.jar & my_dependency_archive.jar), but I only have 1, game.jar. Also, I'm not following the my_pkg.MyClass you are refering to. The class that my jar uses is in a different folder, so do put in an absolute path for that? thanks again.

**Comment by reportmill** [comment]
Ah, if you only have one jar file, it’s that much easier. The documentation is merely trying to provide a template for a common launch.

Just like with Java on the command line, you need to specify a main class that exists in your jar. So if I was going to run the app from the command line, I might type this:

	prompt> java -cp game.jar com.atari.SpaceInvaders

And if I wanted to run it with cheerpj:

	cheerpjRunMain(“com.atari.SpaceInvaders”, “game.jar”);

jeff

**Comment by scottschaffer** [comment]
thanks again Jeff! ok, I think I just need to figure out the first parameter, and I'll be good!

**Comment by alexp-sssup** [comment]
@scottschaffer The first parameter is simply the fully qualified name of the class you want to start. It must be a "main" class for Java (i.e. a class with a ```public static void main(String[] args)``` method).

As a rule of thumb you can always use the equivalent native java commands (as Jeff suggested) to test that your Jar and your class are working correctly before running them using CheerpJ.

**Comment by alexp-sssup** [comment]
They are necessary. The jar.js represent all code which is contained in the original jar, but the Java runtime needs more information than that.

**Comment by scottschaffer** [comment]
I just cant seem to get this to work. In the browser console, the error is either that it cant find the Main Class (the first parameter) or cant find the .jar file (the second parameter). Attached is a screen cap that might help steer me? Thanks for any insight. 
![capture](https://user-images.githubusercontent.com/34664172/34163549-026cfdd4-e4a5-11e7-8a99-e50778301bbe.PNG)

**Comment by scottschaffer** [comment]
Thanks for your help.. I have tried everything, and still not getting it. I
am fairly new to this, so my naivety is surely 100% to blame.. I have
included a link to my Google Drive with my HTML and JAR file. Was wondering
if you could just take a moment to look at it and give me any pointers?
Any help would be appreciated.

https://drive.google.com/drive/folders/1_ky5xcR60CSYVOfCxi6dN-m-zw0nhDs3?usp=sharing

Thanks!

**Comment by alexp-sssup** [comment]
Works without a problem for me. Most probably you are not starting the web server from the directory where the index.html and JAR file are.

**Comment by scottschaffer** [comment]
ahh, ok.. how do I achieve that? It's KILLING me that it worked for you,
haha..

**Comment by alexp-sssup** [comment]
What is the URL you are using in the browser?

**Comment by scottschaffer** [comment]
file:///C:/Users/SS/Desktop/workspace/index.html

**Comment by alexp-sssup** [comment]
That's the error, you need to run CheerpJ using a local Web server, not directly from the disk. Your url must look like http://127.0.0.1/index.html. There are many different web server and plenty of tutorials on the internet on how do start one. If you have python or node.js installed you can using the http server included with them.

**Comment by scottschaffer** [comment]
yes, ok.. I have been looking at that while Ive been emailing with you.. Im
glad to know that the Cheerpj converter worked.. that was my main concern.
I will study on how to get the local server going. I have installed Python,
so I think im on my way.. Thanks so much for your help! I truly appreciate
the extra mile you've gone to help.

**Comment by alexp-sssup** [comment]
Closing.
