### ISSUE TITLE
How can I control the File systems?

### ISSUE THREAD

**Issue by uoau** [leaningtech/cheerpj-meta#131]
Such as, I have a jar, I use it like this in linux,
```
java -jar plantuml.jar ./test.txt
```
I use it use cheerpj.
```
<script>
cheerpjInit();
cheerpjRunJar("plantuml/plantuml.jar", './test.txt');
</script>
```
But I can read the file, How can I let cheerpjRunJa deal the test.txt file ?

**Comment by marsicplusplus** [comment]
Hi @uoau.

To read more about the virtual file system that CheerpJ implements you can take a look at the wiki: https://github.com/leaningtech/cheerpj-meta/wiki/File-System-support

In general you will need to read the file that you have in the root of your webserver from the _/data/_ folder.
