### ISSUE TITLE
change rt.jar.com.js code to include no-cors

### ISSUE THREAD

**Issue by gl91306** [leaningtech/cheerpj-meta#134]
most cors errors can be fixed by changing this bit of code in rt.jar.com.js
`fetch(path, {
    method: jsMethod,
    body: postData,
    headers: myHeaders
}).then(function(response) {
    ......`
to
`fetch(path, {
    method: jsMethod,
    mode: 'no-cors',
    body: postData,
    headers: myHeaders
}).then(function(response) {
    ......`

**Comment by alexp-sssup** [comment]
I think you might be misunderstanding with mode: "no-cors" does. Please read this: https://stackoverflow.com/questions/43262121/trying-to-use-fetch-and-pass-in-mode-no-cors

CORS is a security feature, it cannot be disabled from client side code, by design.
