### ISSUE TITLE
TextDemo from the scratch / regarding the tutorial

### ISSUE THREAD

**Issue by seteahconnoc** [leaningtech/cheerpj-meta#137]
Hello

I was able to follow this instructive tutorial: [https://docs.leaningtech.com/cheerpj/Tutorial.html](https://docs.leaningtech.com/cheerpj/Tutorial.html) The authors made use of this jar file: [https://docs.oracle.com/javase/tutorialJWS/samples/uiswing/TextDemoProject/TextDemo.jar](https://docs.oracle.com/javase/tutorialJWS/samples/uiswing/TextDemoProject/TextDemo.jar) The corresponding java source is found here: [https://docs.oracle.com/javase/tutorial/uiswing/examples/components/TextDemoProject/src/components/TextDemo.java](https://docs.oracle.com/javase/tutorial/uiswing/examples/components/TextDemoProject/src/components/TextDemo.java)

I tried to generate a TextDemo.jar by using TextDemo.java. I managed to execute the jar file on my system. Sadly, I wasn't able to use cheerpj on my jar file.

_I am quite aware, that the task of cheerpj is to get jar files running in a browser - and not to generate generate good java code._

Anyway, it would be quite helpful, if someone could help me on generating a TextDemo example from the scratch (based on a java file). Obviously, I'm using something, that isn't supported by cheerpj. I guess that the documentation of a working example would be easier for the community than analyzing my error logs.

Thanks for cheerpj. Feel free to ask for further details. Any suggestions would be welcome.

---

Debian GNU/Linux 11 (bullseye)
openjdk 11.0.14 2022-01-18
OpenJDK Runtime Environment (build 11.0.14+9-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.14+9-post-Debian-1deb11u1, mixed mode, sharing)

**Comment by alexp-sssup** [comment]
CheerpJ supports only Java 8 at this time. You are building the code using Java 11.

**Comment by seteahconnoc** [comment]
Thank you
