### ISSUE TITLE
Support esoteric audio formats

### ISSUE THREAD

**Issue by ddyer0** [leaningtech/cheerpj-meta#140]
Some (all?) of the sound files trap to the debugger the first time they are played.  I use .au format.

_c4pcQBaicmTasfDZq9EhseHWKg1aIthbbVbjZnSetBytePosieWZWE25 (rt.jar.com.sun.media.sound.js:838)
_c4pcQBaicmTasfDZq9EhseHWKg1aIthbbVjqZcu7apLSKVDonThEn (rt.jar.com.sun.media.sound.js:843)
_c4pcQBaicmTasfDZGnFhseHWKg1aIthbbVfSVrrin3cYtTUeX0xeadrQJecb8iSNo (rt.jar.com.sun.media.sound.js:982)
_c4pcQBaicmTasLCZqn_iqfalrkuTg1aId3cYtV0eq0KiZZI3n (rt.jar.com.sun.media.sound.js:976)
_c4pcQBaicmTasLCZqn_iqfalrkaTg1aId3cYd$ZcaMxn (rt.jar.com.sun.media.sound.js:976)
_c4pbMpGfc4QaQ$yWAfDa0AudioClip4playE4 (rt.jar.sun.applet.js:198)
(anonymous) (VM1949:4)
runContinuationStack (loader.js:489)
cheerpjSchedule (loader.js:1220)
postMessage (async)

...

**Comment by alexp-sssup** [comment]
Not all audio formats/APIs are supported at this stage, due to low interest from commercial users.

Not all the debugger statements though are fatal error, the sounds might work anyway possibly with degraded experience.

**Comment by ddyer0** [comment]
Yes, they do work if I proceed from the debugger, but the behavior wouldn't be acceptable expect at
this early stage of development.  From the use viewpoint the app just hangs until you're smart enough
to open the inspector and punch the contunue button.

**Comment by alexp-sssup** [comment]
> From the use viewpoint the app just hangs until you're smart enough to open the inspector and punch the contunue button.

I am not sure I understand. If the devtools are closed the debugger statements are completely ignored by all browser. The regular users never sees them.

**Comment by ddyer0** [comment]
ok, I guess I always have the debugger open :)

**Comment by epanholz** [comment]
`.au` files are already supported in a nightly build of CheerpJ 3, as long as they are in the right format. This will also be part of the upcoming 3.1 release.

We currently support these sample formats:
- Signed 8-bit PCM
- Unsigned 8-bit PCM
- Signed 16-bit PCM, Little-Endian
- Signed 16-bit PCM, Big-Endian
- Unsigned 16-bit PCM, Little-Endian
- Unsigned 16-bit PCM, Big-Endian
