### ISSUE TITLE
No UDP support

### ISSUE THREAD

**Issue by ddyer0** [leaningtech/cheerpj-meta#141]
I use a udp beacon, which is not strictly needed to run the app, but it traps to the browser debugger
rather then throw a java exception.  I have the recommended network initialization

cheerpjInit({javaProperties:["java.protocol.handler.pkgs=com.leaningtech.handlers"]});

**Comment by alexp-sssup** [comment]
UDP cannot be supported directly since there is no corresponding Web API. Support for arbitrary UDP and TCP is provided via Tailscale: https://labs.leaningtech.com/cheerpj3/guides/Networking#generalized-networking
