### ISSUE TITLE
connection filtering is more restrictive than standard

### ISSUE THREAD

**Issue by ddyer0** [leaningtech/cheerpj-meta#144]
try: http://tantrix.com/Match/match.html

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://tantrix.com:18080/matchserver?wsdl. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

javax.xml.ws.WebServiceException: Failed to access the WSDL at: http://tantrix.com:18080/matchserver?wsdl. It failed with: 
	http://tantrix.com:18080/matchserver?wsdl. [cheerpOS.js:1645:11](https://cjrtnc.leaningtech.com/2.2/cheerpOS.js)

also, this test page:
https://www.boardspace.net/cheerpj/cheer.html
gets a similar error, but the same page, addressed as
https://boardspace.net/cheerpj/cheer.html
is allowed to make the connection

**Comment by alexp-sssup** [comment]
CORS is enforced by the browser and outside of CheerpJ control. I apologize for not closing this bug long ago.
