### ISSUE TITLE
pop-up frames - not quite there

### ISSUE THREAD

**Issue by ddyer0** [leaningtech/cheerpj-meta#145]
The size of pop-up frames seems not quite as specified, and the resulting windows can't
be positioned or sized larger than the original frame established by the javascript.  For 
some reason the first frame is exempt and can be larger.
Also, the pop ups don't have maximize and minimize buttons.
If Using cheerpjCreateDisplay(-1,-1); instead of a fixed size, the pop-ups collapse if you try to move or resize them.

![image](https://user-images.githubusercontent.com/5963076/152623678-f2e7a901-4750-474f-96dc-f26bfaeebd5b.png)

**Comment by ddyer0** [comment]
One other glitch in this app, is that the top-bar menus which appear as "options" "actions" and so on
are nonfunctional.  My best guess is that they are not receiving any mouse events.  You can see this
app in action at https://boardspace.net/hive/hive-viewer.html
The remarkable thing is that this is calling the same jars that would be used by the desktop java
app, which you can invoke as https://boardspace.net/java/boardspace7.jnlp

**Comment by alexp-sssup** [comment]
Most of issues mentioned here are fixed as part of the new CheerpJ 3.0 architecture.

Window resizing and fullscreen support are already tracked here: https://github.com/leaningtech/cheerpj-meta/issues/78

Closing this bug
