### ISSUE TITLE
Converted Java applet crashes on Firefox but works fine on other browsers: Unhandled exception N4java4lang20NullPointerException 

### ISSUE THREAD

**Issue by kacskrz** [leaningtech/cheerpj-meta#150]
**Link:** [https://vonthorn.sarmacja.org/galeria/archive/sarmacja.org/archiwum.sarmacja.org/starwars/](https://vonthorn.sarmacja.org/galeria/archive/sarmacja.org/archiwum.sarmacja.org/starwars/)
**Crash log:**
`unreachable code after return statement [loader.js:4:183]
unreachable code after return statement [loader.js:4:741]
unreachable code after return statement [loader.js:4:526]
java.lang.NoClassDefFoundError:Reporting error: Unhandled exception N4java4lang20NullPointerException /_c4pbQxrZtgmxb$c9O2ZZcX0lcHfrunpqrniq8c0JYeChangedE4,_c4pbMpGfc4QaQkqZbRv0bpNc0qSu3pGi9amjCyefi7vr0m5vRd,ec4pbMpGfc4QaQkqZbRv0bsNc0qS0hr1u6amqe5zJd,em4VanJm3cGKuPdabzjaMczqrpiS3o,_c4pbMpGfc4QaQkqZbRv0bmNc0qSChr14zxd,_n4FZThread3runE22 [loader.js:3207:10]
Unhandled exception N4java4lang20NullPointerException /_c4pbQxrZtgmxb$c9O2ZZcX0lcHfrunpqrniq8c0JYeChangedE4,_c4pbMpGfc4QaQkqZbRv0bpNc0qSu3pGi9amjCyefi7vr0m5vRd,ec4pbMpGfc4QaQkqZbRv0bsNc0qS0hr1u6amqe5zJd,em4VanJm3cGKuPdabzjaMczqrpiS3o,_c4pbMpGfc4QaQkqZbRv0bmNc0qSChr14zxd,_n4FZThread3runE22`

The applet works fine on Opera GX, Chrome and Microsoft Edge; for some reason it refuses to run on Firefox. I can provide JAR file if needed.

**Comment by marsicplusplus** [comment]
Hi @kacskrz.
I'm unable to make the application start both on Firefox and on Chrome, might be because of Cloudflare caching some older version?

From the error it seems like the outputted js from the compilation has been manually altered. Have you done this on purpose? If so, we can't guarantee that the application will always work. 
If that's not the case you should also try to disable CloudFlare Javascript optimizations, as it might be CF itself tampering our compiled code.

Best,
Lorenzo

**Comment by kacskrz** [comment]
No, I haven't made any changes in JS, only on the HTML file (adjusting the parameters to CheerpJ syntax, adding loader.js and so on).
I have just checked it in Chrome, [works fine for me](https://imgur.com/a/olOfjqS) (and worked fine for other people I've asked about it).

**Comment by marsicplusplus** [comment]
As I said, could you please check for CloudFlare js optimizations?

**Comment by kacskrz** [comment]
Unless there's an option to do it without access to Cloudflare panel, I can't (as I don't have access to the panel).

**Comment by kacskrz** [comment]
No, I am not able to reproduce it on my XAMPP. It works fine on Firefox. I've also checked another server without cloudflare - it works fine. I will ask the server administrator about that.
Thanks for your help!
