### ISSUE TITLE
Invoke dynamic not supported?

### ISSUE THREAD

**Issue by priand** [leaningtech/cheerpj-meta#151]
I have some code compiled with Java 17 on Mac.
Failure compiling xxxx/Snippet.class
command: /Users/priand/temp/cheerpj/bin/cheerpj -llvm -llvm-exceptions -cp /var/folders/yg/x7ktz18n5zv4tsy7cm1ymd6m0000gn/T/tmp5zgs_eqi/rt.jar.dir/ xxxx/Snippet.class
Loading class xxxx/Snippet and dependencies
Could not open class java/lang/invoke/StringConcatFactory
Unsupported LLVM generation for opcode ba
In function tryTextResource
Assertion failed: (false), function compileOpcode, file CheerpJCompilerMethod.cpp, line 2349.
SUPPORT CONSTANT 8

**Comment by carlopi** [comment]
CheerpJ currently expect Java 8 as input, and this is likely to be the source of the problem.

Depending on the codebase it may be possible to render it compatible with Java 8, otherwise I would recommend to evaluate CheerpJ with an alternative project based on Java 8.

**Comment by priand** [comment]
Thank you - Java 17 is a requirement for me. Do you have any plan to upgrade?

**Comment by carlopi** [comment]
Work is currently being carried on to support other Java versions (and their runtimes).

For commercial interest, do get in touch with info@leaningtech.com and you might further discuss your use-case / timeline & other relevant issue.

Thanks!
