### ISSUE TITLE
OS.js as screen

### ISSUE THREAD

**Issue by OCTAGRAM** [leaningtech/cheerpj-meta#16]
Swing windows are nice, but their control elements are ugly. Title is barely enough to be read, close buttons look misplaced.

I would like to use OS.js as screen, but there are no hooks to achieve it correctly. com.leaningtech.cheerpj.CheerpJDisplay is opaque. It probably should better be an implementation of customizable interface or abstract class.

**Comment by alexp-sssup** [comment]
Most of the visual details for Swing/AWT windows is defined using CSS, they are currently fixed but we could make them user selectable. Would that be enough for your purpose? If not, what additional features/hook would you need?

**Comment by OCTAGRAM** [comment]
No, CSS is not enough. OS.js has a sort of window manager mimicking Ubuntu. It puts window buttons on taskbar. So it synchronizes titles, it should know what buttons do the windows have and when windows change available buttons. Custom window manager can send maximize/minimize events. Also, window manager should have an idea about modality relations. Modal dialog windows should not have a button on taskbar. Instead, when user clicks on an application window button, window manager should be able to put on top every window involved in modal blocking in the same order as they were blocking each other. And window manager should do the same when user clicks on any blocked window.

I am writing from scratch. I am investigating if I can achieve good desktop-looking UI with Swing MDI. That won't work for existing applications' code, but for my code at least.

**Comment by alexp-sssup** [comment]
Supporting externally provided windows system is outside the scope of the project. Closing.
