### ISSUE TITLE
Function `cheerpjAddStringFile` not available on `loader.js`

### ISSUE THREAD

**Issue by apolinario** [leaningtech/cheerpj-meta#160]
Despite being mentioned on https://docs.leaningtech.com/cheerpj/File-System-support, the function `cheerpjAddStringFile` does not seem to be available on https://cjrtnc.leaningtech.com/2.3/loader.js or in [this](https://github.com/leaningtech/cheerpj-meta/issues/158#issuecomment-1432707739) latest runtime https://cjrtnc.leaningtech.com/20230216/loader.js

<img width="432" alt="image" src="https://user-images.githubusercontent.com/788417/219378411-746a841d-687f-41bf-932a-8bde2a5de5ce.png">

**Comment by alexp-sssup** [comment]
The function is implemented in `cheerpOS.js` which is loaded after cheerpjInit is completed
