### ISSUE TITLE
StackTraceElement.html#getFileName() returns null

### ISSUE THREAD

**Issue by tytot** [leaningtech/cheerpj-meta#162]
I have an executable (Java Swing) JAR that I converted using CheerpJ 2.3 on Ubuntu. When I try to run the application in an HTML page per the tutorial, the frame remains white and I get an `Unhandled exception N4java4lang20NullPointerException /` in the console.

Minimal reproducible example: https://github.com/tytot/cheerpj-demo

**Comment by bates64** [comment]
[CheerpJ 3.0 is now available](https://labs.leaningtech.com/blog/cheerpj-3.0). Let us know if you still have this issue using CheerpJ 3.0 @tytot. As Alessandro said, the application is arguably buggy, but it might work now anyway.

**Comment by bates64** [comment]
Awesome!
