### ISSUE TITLE
Failed to compile JEdit

### ISSUE THREAD

**Issue by 2dpdlja496or43iq** [leaningtech/cheerpj-meta#163]
You presented a screenshot of JEdit running on the browser. I tried to compile the latest stable version of JEdit and it failed.

**Comment by alexp-sssup** [comment]
Please make sure the version you want to compile is based on Java 8, that's the only version supported by CheerpJ.

If it is based on Java 8, please provide a link to the exact JAR you are trying to compile.

**Comment by 2dpdlja496or43iq** [comment]
> Please make sure the version you want to compile is based on Java 8, that's the only version supported by CheerpJ.
> 
> If it is based on Java 8, please provide a link to the exact JAR you are trying to compile.

The latest stable version of JEdit requires Java 11. You should make it clear on the project's page that it only supports Java 8.

**Comment by alexp-sssup** [comment]
The Java 8 limitation will soon be removed, we will support Java 9+ as part of the CheerpJ 3.x architecture that will be released during summer of 2023.
