### ISSUE TITLE
How does CheerpJ compared to other solutions?

### ISSUE THREAD

**Issue by PHdrr** [leaningtech/cheerpj-meta#168]
Please have a look: https://github.com/jashkenas/coffeescript/wiki/List-of-languages-that-compile-to-JS#javajvm

To be more clear, I wanted to know how CheerpJ compared to JSweet, TeaVM and Java2Script/SwingJS.

**Comment by alexp-sssup** [comment]
We cannot provide detailed comparisons across every alternative.

CheerpJ is designed to efficiently run large scale Java applications, including AWT and Swing, in the browser without any modification to the original code.
