### ISSUE TITLE
Missing libarc.so

### ISSUE THREAD

**Issue by 5UP3R-D1N** [leaningtech/cheerpj-meta#171]
e

**Comment by alexp-sssup** [comment]
Could you clarify what you mean? CheerpJ does not depend on libarc in any way

**Comment by 5UP3R-D1N** [comment]
Basically my jar use libarc

**Comment by alexp-sssup** [comment]
CheerpJ is only intended to run application completely written in Java. There is no support for native x86 libraries.

In the future we might offer a C/C++ JNI re-implementation and allow users to recompile JNI modules directly to Wasm for use with CheerpJ, but this not currently a priority.
