### ISSUE TITLE
nullpointerexception

### ISSUE THREAD

**Issue by KotwGrone96** [leaningtech/cheerpj-meta#173]
Hi everyone! i'm trying to open a PHET file from https://phet.colorado.edu/
there are many JAR files. After run python script and start my local server in python y have the next error in browser's console "java.lang.nullpointerexception". Does anyone can help me?

**Comment by alexp-sssup** [comment]
Unfortunately we don't have enough information right now to help you effectively.

Please consider following the CheerpJ tutorial before attempting something more complex.

https://docs.leaningtech.com/cheerpj/Tutorial

Can you also publish the web page you wrote so that we can take a look?

**Comment by alexp-sssup** [comment]
Closing due to lack of information
