### ISSUE TITLE
Resetting the Classloader / static fields after program execution.

### ISSUE THREAD

**Issue by BlazingTwist** [leaningtech/cheerpj-meta#174]
Currently it seems that class initialization is only run once.
As a result Java code such as this causes "unexpected" behaviour:
```java
package blazingtwist;

public class Main {
    public static String myStaticVariable = null;

    public static String getMyStaticVariable(String initializer) {
        if (myStaticVariable == null) {
            myStaticVariable = initializer;
        }
        return myStaticVariable;
    }

    public static void main(String[] args) {
        String myVariable = getMyStaticVariable(args[0]);
        System.out.println("myVariable is '" + myVariable + "'");
        System.exit(0);
    }
}
```

Executing the Main class like this:
```js
cheerpjInit();
cheerpjRunMain("blazingtwist.Main", "/app/CheerpJTesting.jar", "hello");
cheerpjRunMain("blazingtwist.Main", "/app/CheerpJTesting.jar", "world");
```

Results in this output:
```
myVariable is 'hello'
myVariable is 'hello'
```

Whereas the expected output would be:
```
myVariable is 'hello'
myVariable is 'world'
```

The same behaviour occurs for
```js
cheerpjRunJar("/app/CheerpJTesting.jar", "hello");
cheerpjRunJar("/app/CheerpJTesting.jar", "world");
```

---

Obviously "fixing" that example is trivial, but for more complicated programs this preservation of static fields causes a lot of unexpected side effects.

Ideally there would be some way to restart the JVM / or re-run all static initializers, such that subsequent `cheerpjRunMain` calls start from a fresh slate.

For completeness sake, I have attached the full source code / jar / jar.js
[source.zip](https://github.com/leaningtech/cheerpj-meta/files/12709059/source.zip)

---

Just to clarify, this does provide the expected output:
```
java -jar .\CheerpJTesting.jar "hello"
java -jar .\CheerpJTesting.jar "world"
```

**Comment by alexp-sssup** [comment]
The behavior you observed is expected with the CheerpJ 2.x architecture, which is currently being deprecated in favor of the new CheerpJ 3. CheerpJ 3 will behave correctly for this test case.

A first release candidate CheerpJ 3.0 will be made available in mid-october, but you can already try out current builds. Please join our Discord for more information: https://discord.gg/X9ruPkchM5
