### ISSUE TITLE
Issue with running the example

### ISSUE THREAD

**Issue by anusurendra** [leaningtech/cheerpj-meta#177]
Hi,

I am trying to run the TextDemo.jar example. I am not able to run it 
```

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>CheerpJ test</title>
    <script src="https://cjrtnc.leaningtech.com/3.0rc2/cj3loader.js"></script>
  </head>
  <body>
    <script>
      (async function () {
        await cheerpjInit();
        cheerpjCreateDisplay(800, 600);
        await cheerpjRunJar("/var/www/compLiMet/public_html/dev_site/VaLID/TextDemo.jar");
      })();
    </script>
  </body>
</html>
```

I am also attaching a screenshot of the error.
![CheerpJ](https://github.com/leaningtech/cheerpj-meta/assets/5685804/f4ae7cad-3d14-4017-bc89-5ec7a78b5f04)

**Comment by alexp-sssup** [comment]
`cheerpjRunJar` takes paths as in the CheerpJ virtual filesystem. You have instead used a path on your local system.

Please follow the tutorial step by step. https://labs.leaningtech.com/cheerpj3/getting-started/Java-app

**Comment by anusurendra** [comment]
Hi,

I followed the instructions and now I am getting the following issues (screenshots attached). The code is written in VSCode and when I compile it in VSCode it runs without errors. Not sure why I get this error.

![CheerpJerror1](https://github.com/leaningtech/cheerpj-meta/assets/5685804/37afd9ac-35b4-4bcf-86d5-80d9cccb22a3)
![CheerpJerror2](https://github.com/leaningtech/cheerpj-meta/assets/5685804/8d7f7a2e-f854-44bc-b936-878e8caca71e)

**Comment by alexp-sssup** [comment]
There is no useful information on these screenshots. I do notice some logging that might suggest that the page is interactive with the CheerpJ private `c.html` iframe. Please make sure the page is not breaking the iframe and that you have no extensions installed.

I would recommend taking a good look at the exception trace. You might find useful information there.

Consider joining our Discord for support, there is most likely some mistake in the way CheerpJ is used, no actual bug.

https://discord.gg/X9ruPkchM5
