### ISSUE TITLE
Missing import:"_ZNK3icu9MarkArray12getMarkClassERKNS_16LETableReferenceEjiPKNS_14LEFontInstanceER7LEPointR11LEErrorCode"

### ISSUE THREAD

**Issue by JacobDK123** [leaningtech/cheerpj-meta#178]
I am running a smal .jar file that works on my desktop under Java 8.
Under cheerpJ 3_20240124_349/cj3loader.js  is reaches "Graphic system initializing" and then stops, with only one line in the console:
"Missing import:"_ZNK3icu9MarkArray12getMarkClassERKNS_16LETableReferenceEjiPKNS_14LEFontInstanceER7LEPointR11LEErrorCode"
in c3j.js:1:411927 

https://cjrtnc.leaningtech.com/3_20240124_349/cj3.js

Thanks,
/Jacob

**Comment by alexp-sssup** [comment]
I'll attempt a blind fix, but please _always_ provide a test case. Possibly a minimal one, even better if on JavaFiddle (https://javafiddle.leaningtech.com)

**Comment by JacobDK123** [comment]
OK, also if this is old code that I do not have any source code for? Thus the only thing I could do was to provide the .jar-file as example.

**Comment by alexp-sssup** [comment]
We never need source code. CheerpJ works exclusively from jar files.

Please try this build first: https://cjrtnc.leaningtech.com/3_20240126_356/cj3loader.js

**Comment by JacobDK123** [comment]
Sorry, for https://cjrtnc.leaningtech.com/3_20240126_356/cj3.js this leads to:
Missing import: _ZNK3icu11AnchorTable9getAnchorERKNS_16LETableReferenceEjPKNS_14LEFontInstanceER7LEPointR11LEErrorCode cj3.js:1:412005

This runnable .jar is not that important, thus, feel free to close the issue as won't fix.

**Comment by alexp-sssup** [comment]
We can fix the issue, but the we need the example, otherwise I can fix one small problem at a time.
