### ISSUE TITLE
Generic Field Types not supported

### ISSUE THREAD

**Issue by BrunoEberhard** [leaningtech/cheerpj-meta#18]
In [Minimal-J](http://minimalj.org/) I rely much on reflection. One thing that seems not to work are the generic Types of Fields:

```
public class ListContainer {

	public List<String> strings;
}

public class FieldTypes {

	public static void main(String[] args) throws Exception {
		Field field = ListContainer.class.getField("strings");

		System.out.println("Field.genericType should be implementation of " + ParameterizedType.class.getSimpleName());
		Type type = field.getGenericType();
		System.out.println("Actual value: " + type);
	}

}
```

This returns java.util.List with CheerpJ but java.util.List<java.lang.String> with JDK 8.

regards

Bruno

**Comment by alexp-sssup** [comment]
This problem is fixed in current cheerpjunstable.

**Comment by BrunoEberhard** [comment]
**Not** working in 1.0

**Comment by alexp-sssup** [comment]
This is now actually fixed in our ```latest``` endpoint. (i.e. ```https://cjrtnc.leaningtech.com/latest/loader.js```)
