### ISSUE TITLE
java.io.FileNotFoundException ocurred when create fileInputStream

### ISSUE THREAD

**Issue by aidscooler** [leaningtech/cheerpj-meta#180]
the issue I opened yesterday [java.io.FileNotFoundException ocurred when create fileInputStream](https://github.com/leaningtech/cheerpj-meta/issues/179#issue-2103208984)
I mean the exception was occured at this code: const fileStream = await new FileInputStream(file)
it seems the argument file is taken as a file path,actually it is a File type argument.
I'm also wondering if there is anyway to run CheerpJ locally,because some .jar file couldn't be downloaded due to network problem , see the error message below :
GET https://cjrtnc.leaningtech.com/3.0rc2/8/resources.jar net::ERR_CACHE_OPERATION_NOT_SUPPORTED
I've noticed this problem several times and the name of .jar file which couldn't be downloaded is different everytime.
![QQ截图20240127122049](https://github.com/leaningtech/cheerpj-meta/assets/22463546/7f5b09b7-bcfa-45dc-98d5-b731f2656808)

**Comment by alexp-sssup** [comment]
I am not sure what `File` is here, is that a JavaScript File type? That is obviously not something can Java code can directly use.

You can load the File data from JavaScript and store it into the `/str/` filesystem. See here for more info: https://labs.leaningtech.com/cheerpj3/guides/File-System-support#str-mount-point

`ERR_CACHE_OPERATION_NOT_SUPPORTED` is a message from the browser and not an actual error.

Self-hosting CheerpJ is possible, but only for commercial users.
