### ISSUE TITLE
Application freezes

### ISSUE THREAD

**Issue by TerraStudio** [leaningtech/cheerpj-meta#187]
I work at a school, where we try to convert "Filius" (a software for simulating network communcation" to JS,
since it can't be used on iPads.

I added my project as an attachment.
The source code of Filius is taken from: https://gitlab.com/filius1/filius/-/tree/v1.14.2?ref_type=tags
I compiled it with all dependencies included.

When I start it, I can add a PC with drag and drop. But then I click on Run and the simulation starts. You can click on the PC and install software on it. But when I choose a software and want to add it, the application freezes and I have to close the tab.

Unfortunately there is no error message in the console.
Do you have a way to see more information about why it crashed?

[config.zip](https://github.com/leaningtech/cheerpj-meta/files/14310218/config.zip)

**Comment by alexp-sssup** [comment]
We have identified that the version of slf4j used by this app depends on NoSuchMethodError's being thrown, which is not currently supported by CheerpJ. We have added this issue to our internal bug tracker, but it might take some time before is fixed.

**Comment by TerraStudio** [comment]
@alexp-sssup  Thanks for the tip with slf4j. By using a regex in a python script, I managed to delete all occurrences of slf4j and then recompiled it. Now it works!

**Comment by TerraStudio** [comment]
@alexp-sssup The touch on mobile devices doesn't work. Do you know a solution?

**Comment by alexp-sssup** [comment]
Mobile is currently not officially supported, there is no solution at this time. It's a known issue:

https://github.com/leaningtech/cheerpj-meta/issues/110

**Comment by TerraStudio** [comment]
But was this also a problem in cheerpj 2.3?

**Comment by alexp-sssup** [comment]
Yes, nothing has changes in the AWT implementation

**Comment by bates64** [comment]
Going to close this as it was resolved (https://github.com/leaningtech/cheerpj-meta/issues/187#issuecomment-1951473236). Mobile support is tracked in https://github.com/leaningtech/cheerpj-meta/issues/110.

**Comment by alexp-sssup** [comment]
I am happy to report that the original issue is fixed in the following build: https://cjrtnc.leaningtech.com/3_20250402_958/cj3loader.js

Moreover, thanks to recent improvements in CheerpJ, the application should now work on mobile.
