### ISSUE TITLE
applet does not start

### ISSUE THREAD

**Issue by mstarPW21** [leaningtech/cheerpj-meta#188]
For about two years the applet on the page
https://www.polyhedra-world.nc/stuff/AniKa/anim_.html
worked perfectly thanks to the help provided on this forum.
I just noticed that it no longer starts, which leaves me perplexed.
I don't remember having made any changes in the /AniKa/ directory.
Thank you in advance for your help.
​

**Comment by alexp-sssup** [comment]
There has been no change on the CheerpJ side, our builds are immutable.

What has changed is that `javaview.jar` is not available anymore and returns 404. It might be the case that the website migrated hosting and did not correctly preserve the JAR.

You can find an archived copy of the JAR here, you might be able to restore the website with this copy: https://web.archive.org/web/20220730063916/https://www.polyhedra-world.nc/stuff/AniKa/javaview.jar
