### ISSUE TITLE
getFields() on primitive type crashes

### ISSUE THREAD

**Issue by BrunoEberhard** [leaningtech/cheerpj-meta#19]
To ask for the fields of a primitive Type doesn't make sense but should not crash the system

```
public class FieldsOfPrimitive {

	public static void main(String[] args) throws Exception {
		System.out.println(Integer.TYPE.getFields());
		System.out.println("Still alive");
	}
}
```

This returns works with with JDK 8 but CheerpJ produces:
Unhandled exception N4java4lang20NullPointerException/TypeError: Cannot read property 'length' of null

regards

Bruno / minimalj.org

**Comment by alexp-sssup** [comment]
This bug was fixed with 1.0.
