### ISSUE TITLE
requestAnimationFrame not supported in this Worker.

### ISSUE THREAD

**Issue by JoseVSeb** [leaningtech/cheerpj-meta#192]
I'm trying to load cheerpj in a web worker (vscode web extension language server). it throws the following error when loading a [jar file](https://github.com/google/google-java-format/releases/download/v1.21.0/google-java-format-1.21.0-all-deps.jar) in chromium browser:
```
Uncaught DOMException: Failed to execute 'requestAnimationFrame' on 'DedicatedWorkerGlobalScope': requestAnimationFrame not supported in this Worker.
```
I first thought it had something to do with vscode web extension limitations but it loads without the error when testing on firefox.
please help.

**Comment by alexp-sssup** [comment]
Can you provide the complete integrated HTML + JavaScript code? Ideally deployed on a publicly accessible URL.

**Comment by alexp-sssup** [comment]
The problem should we fixed with the following build: https://cjrtnc.leaningtech.com/3_20240315_458/cj3loader.js

Please try again, we could not verify ourselves since a complete test case was not provided.

**Comment by JoseVSeb** [comment]
The issue is resolved.
But it didn't amount to much, since the jar file I was trying to load needed Java 11 and Cheerpj only supports 8. It was an unfortunate oversight from my end.
Sorry for the inconvenience caused.
