### ISSUE TITLE
java.lang.UnsatisfiedLinkError on java.util.zip.Adler32.updateBytes

### ISSUE THREAD

**Issue by AlexeyAnischenko** [leaningtech/cheerpj-meta#193]
Trying to run [Azul's GC Log Analyzer ](https://docs.azul.com/prime/GC-Log-Analyzer) under CheerpJ.
Direct link for the [ jar download](https://cdn.azul.com/gcla/GCLogAnalyzer2.jar).   

I copied the jar to my http server, near the index.html with the following content (bad formatting here, see the screenshot below):

> <!doctype html>
> <html lang="en">
>   <head>
>     <meta charset="utf-8" />
>     <title>CheerpJ test</title>
>     <script src="https://cjrtnc.leaningtech.com/3.0/cj3loader.js"></script>
>   </head>
>   <body>
>     <script>
>       (async function () {
>         await cheerpjInit();
>         cheerpjCreateDisplay(1900, 1000);
>         await cheerpjRunJar("/app/GCLogAnalyzer2.jar", "/app/sample-gc.log");
>       })();
>     </script>
>   </body>
> </html>
> 

The application loads, displays the UI, then tries to open the gc.log provided (you can use any GC.log available), and then fails to load it, displaying the "java.lang.UnsatisfiedLinkError on java.util.zip.Adler32.updateBytes" messagebox.

Another problem (dupe of https://github.com/leaningtech/cheerpj-meta/issues/105) is  app's "File->Open" dialog displays just the empty window with "open file" button, while there are several files in the /app root of my webserver, and I am then unable to close the "open file" dialog.

running the same app the usual way with java8 openjdk  "java -jar GCLogAnalyzer2.jar sample-gc.log" works just fine

**Comment by AlexeyAnischenko** [comment]
![azul-churpj-gcla](https://github.com/leaningtech/cheerpj-meta/assets/12764321/008bb4cf-81c8-40b1-bce1-4cc2c648764d)
![image](https://github.com/leaningtech/cheerpj-meta/assets/12764321/a0bf7f3a-98cd-452e-b7d6-cdde721a0d45)

**Comment by AlexeyAnischenko** [comment]
File->Open dialog displays just that
![image](https://github.com/leaningtech/cheerpj-meta/assets/12764321/afbc0041-1195-4926-88db-2afa3c9b20e5)

**Comment by AlexeyAnischenko** [comment]
The file open dialog is a separate known issue
https://github.com/leaningtech/cheerpj-meta/issues/105

**Comment by epanholz** [comment]
The issue should be resolved with this build: https://cjrtnc.leaningtech.com/3_20240326_462/cj3loader.js

**Comment by AlexeyAnischenko** [comment]
Confirming that the newer loader version fixes the problem, thx!
