### ISSUE TITLE
Several applets on a page, but only one works

### ISSUE THREAD

**Issue by mobluse** [leaningtech/cheerpj-meta#197]
I have three applets (same applet, but loaded with different Java ME apps) on http://df.lth.se.orbin.se/~mikaelb/microemu/all.html , but only one (the rightmost) is running correctly using https://cjrtnc.leaningtech.com/3.0/cj3loader.js. Here you can see all files in the folder: http://df.lth.se.orbin.se/~mikaelb/microemu/. The applets should not communicate with each other. The applets work individually using their own pages:
http://df.lth.se.orbin.se/~mikaelb/microemu/blockis.html
http://df.lth.se.orbin.se/~mikaelb/microemu/aritm.html
http://df.lth.se.orbin.se/~mikaelb/microemu/weekno.html

![Skärmbild 2024-07-10 182907](https://github.com/leaningtech/cheerpj-meta/assets/5777329/13951aa0-f4a8-4c32-b0e9-b9d187facee7)
If I use CheerpJ 2.3, using the orange button (shield with bean), it loads the wrong apps into the applets and if I click buttons in one applet it changes things in another.

Here is how it should look (IE mode in Edge using Java 8):
![Skärmbild 2024-07-10 182719](https://github.com/leaningtech/cheerpj-meta/assets/5777329/391af28b-b451-4985-b1f4-a2c3aa521742)
I prefer to be able to use CheerpJ since not all users have Edge and Java 8 installed and know how to configure Java security.

**Comment by alexp-sssup** [comment]
Please try again with the following build: https://cjrtnc.leaningtech.com/3_20240721_512/cj3loader.js

There was a subtle bug in classloader sharing when applets use different sets of jars
