### ISSUE TITLE
iframe inconsistencies, issues loading jar

### ISSUE THREAD

**Issue by thenickman100** [leaningtech/cheerpj-meta#203]
## Overview:
I am trying to load an iframe with a CheerpJ java applet inside.  Normally, this gives no issues.  Trying to do this technique with the J2ME MicroEmulator is not working, and there are inconsistencies in behavior between using the CheerpJ Applet Runner browser extension and loading CheerpJ from within the html files.

### Case 1: Open iframe file separately, cj3loader and init both in page
- Everything loads properly

### Case 2: Open parent document with embedded iframe.  iframe contains the cj3loader and init
- MicroEmu wrapper loads, embedded J2ME game does not load.
```
Exception in thread "AWT-EventQueue-1"
java.lang.IllegalArgumentException: Width (240) and height (0) cannot be <= 0
```

### Case 3: Open parent document with embedded iframe.  Parent document contains the cj3loader and init
- Nothing loads

### Case 4: Open parent document with embedded iframe.  Use applet runner extension
- Everything loads properly

## Questions:
Why does the applet runner extension not experience any issues running the iframe and its contents? Is there any way to initialize CheerpJ in a way that mimics the applet runner extension?

Why would running the applet in an iframe lead to CheerpJ miscomputing the height of something?  Is there a different way to initialize the applet inside the iframe to prevent this miscalculation?

## Demo:
Here is a zip with example files: [demo.zip](https://github.com/user-attachments/files/18001346/demo.zip)

Link to microemu repository: https://github.com/barteo/microemu

**Comment by epanholz** [comment]
Hello,

Thank you for forwarding us the demo, I was able to download the files and could reproduce the error you mentioned. I will need some time to further look into the problem and get to the bottom of the issue.

I will let you know once I fixed it and will share a new loader with you.

**Comment by epanholz** [comment]
Hello again,

The issue should be fixed in this newer build `https://cjrtnc.leaningtech.com/3_20241206_566/cj3loader.js`.

**Comment by thenickman100** [comment]
Thank you!
