### ISSUE TITLE
caching cjCall

### ISSUE THREAD

**Issue by norzak** [leaningtech/cheerpj-meta#21]
Is there a way to cache the method called with cjCall for performance?

**Comment by alexp-sssup** [comment]
Not at this time, but we could introduce an additional API (for example, ```cjResolve```) to let the user control and cache the resolution of Java methods directly from JS.

Do you have a specific use case in mind where the current cjCall performance could be a problem?

**Comment by alexp-sssup** [comment]
Explicit resolving/caching of methods is now supported in current latest endpoint ```https://cjrtnc.leaningtech.com/latest/loader.js```. For docs see here: https://github.com/leaningtech/cheerpj-meta/wiki/Runtime-API#cjresolvecall--cjresolvenew
