### ISSUE TITLE
Inline native JavaScript method declaration via Annotations

### ISSUE THREAD

**Issue by neuronsupport** [leaningtech/cheerpj-meta#22]
Any plans to support inline native JavaScript method declaration via Annotations?

**Comment by alexp-sssup** [comment]
You can see our current JS interoperability support here: https://github.com/leaningtech/cheerpj-meta/wiki/Implementing-Java-native-methods-in-JS. It is not nice, but it is very powerful. We are currently working on providing a cleaner API, and we could consider annotations, but other methods may also be used.

Can you elaborate on the reasons why annotations would be your favourite solution?

**Comment by alexp-sssup** [comment]
We deem implementing JS methods via annotations to go against the concept of CheerpJ being a compiler and not a library or framework.

On the other hand, as part of the new CheerpJ 3.0 architecture, there is powerful support for implementing native methods directly in JavaScript with a convenient syntax and async support.

For more info: https://labs.leaningtech.com/cheerpj3/guides/Implementing-Java-native-methods-in-JavaScript
