### ISSUE TITLE
Applet Parameter tags

### ISSUE THREAD

**Issue by BCADCurry** [leaningtech/cheerpj-meta#24]
My applet uses a few parameters so that the names of various XML input files can be passed to the applet. Once the names of these files are passed to the applet, the applet reads the files in.

In the HTML document where my applet is called, I have various Param tags as follows:

```
    <PARAM NAME=template VALUE="mytemplate.xml" />
    <PARAM NAME=properties VALUE="properties.xml" />
```

How do I pass these parameters to CheerpJ?

For the record, I am trying to port the applet version of my project over as I believe this is primarily what CheerpJ is for. However, I also have a version which is a standalone application. The standalone application does not require the PARAM tag to get the names of the input files.

**Comment by alexp-sssup** [comment]
When porting applets to CheerpJ there is no need to change the page markup. Parameters will be automatically loaded from the <param> tags.

As documented [here](https://github.com/leaningtech/cheerpj-meta/wiki/Getting-Started#converting-an-applet) to run the applet you only need to include the ```loader.js``` script from our CDN endpoint, and call cheerpjInit. To avoid possible confusion with native Java we recommend replacing the object/applet/embed tags with cheerpj-object/cheerpj-applet/cheerpj-embed.

Moreover, CheerpJ actually supports full Java applications, not only applets.

**Comment by BCADCurry** [comment]
Thanks for letting me know. I was just looking for some sort of explanation for why my applet isn't working when I try to run it with the cheerpjfy.py generated JS file. The JS file was generated perfectly well with no errors.

Another thing I've observed is that my applet can be rendered by the CheerpJ Chrome extension. However, if I place the JS file I generated with cheerpjfy.py in the same directory as the applet JAR file, the CheerpJ Chrome extension will no longer interpret the applet.

**Comment by BCADCurry** [comment]
Thanks for the feedback Alessandro. Oddly enough, when I place the file:
bikeCADPro.jar.js on my site, the CheerpJ Chrome extension no longer runs
my applet. Hopefully, you can see what I mean at:
https://www.bikecad.ca/quickapplet

Regards,

Brent

**Comment by alexp-sssup** [comment]
Are you using the Beta 3 AOT compiler? If so there was a bug in that release that prevents the compiled version to run. The bug is now fixed. We are going to release a public new version very soon. If you are interested in early access to a new build please get in touch with us in private.

**Comment by BCADCurry** [comment]
Yes, I was using cheerpj_win_preview_beta_3_20171107. Looking forward to trying the corrected version.

Thanks

**Comment by alexp-sssup** [comment]
Closing.

**Comment by BCADCurry** [comment]
Thanks! The new AOT compiler works great.
