### ISSUE TITLE
Cheerpj crashes when reading files

### ISSUE THREAD

**Issue by ferdinandmehlan** [leaningtech/cheerpj-meta#25]
Our cheerpj-translated project seems to crash when trying to read a file. The file exists in the virtual filesystem cheerpj uses.

**Comment by alexp-sssup** [comment]
We need more details to understand your issue. Can you provide a reproducible test case? Filesystem code is heavily used both by us and by our customers, so if there is a problem it must be specific to your application or setup.

**Comment by alexp-sssup** [comment]
Closing due to lack of information. Please reopen if you can provide a reproducible test case.
