### ISSUE TITLE
CheerpJCompression.cpp / getIdentifierBase64Value

### ISSUE THREAD

**Issue by BrunoEberhard** [leaningtech/cheerpj-meta#26]
After translation with CheerpJ 1.0 my application fails with attached output. With beta 3 I didn't have this behaviour.

What can be done?
[cheerpj_1.0_output.txt](https://github.com/leaningtech/cheerpj-meta/files/1838376/cheerpj_1.0_output.txt)

**Comment by alexp-sssup** [comment]
Is there a publicly accessible test we can use to reproduce the problem?

**Comment by BrunoEberhard** [comment]
No, but I will try to narrow it down as soon as I find the time. I hoped you recognize a pattern or method name.

**Comment by BrunoEberhard** [comment]
Sorry, duplicate of

[package annotations #20](https://github.com/leaningtech/cheerpj-meta/issues/20)
