### ISSUE TITLE
Problem running a compiled app

### ISSUE THREAD

**Issue by escalope** [leaningtech/cheerpj-meta#27]
Hi

I have successfully compiled this app (it's open source) 
[app.jar](https://drive.google.com/file/d/1vVIsnSqq6340tCFG0wRDCSs-_Pb1bQf8/view?usp=sharing)
 and run it with the corresponding web page.

Initially, it looked gorgeous
![image](https://user-images.githubusercontent.com/3056482/37826769-19f4b7e6-2e95-11e8-9da7-022b535566de.png)

But, when creating a diagram (right click in the top left tree) and then opening the diagram (double click in the top left tree in the new entry) and creating an entry (in the right side, press any of the toolbar buttons) it returned many mistakes.

I checked in gitter and I was told it maybe problem of the cheerpj. Here is the attached log.

[localhost-1521804526088.log](https://github.com/leaningtech/cheerpj-meta/files/1841326/localhost-1521804526088.log)

I am running on a Chrome Version 65.0.3325.146 (Official Build) (64-bit) under linux.

Thanks in advance

Regards

**Comment by escalope** [comment]
Forgot to mention that this is what should have happended
![image](https://user-images.githubusercontent.com/3056482/37827114-77564f02-2e96-11e8-91a8-66fe88f8700a.png)

**Comment by escalope** [comment]
And the error my app detects has to do with the parsing of some XML files. If they are not parsed, the app does render nothing. I had to use a very specific xerces version which was embedded in the jar. If other was used, I always run into troubles. Maybe it is a collision with other existing xerces cheerpj adds during the conversion?

**Comment by alexp-sssup** [comment]
@escalope, I can't see the JAR. Are you sure you have attached it? Or is there a link somewhere which I am not finding.

**Comment by escalope** [comment]
Sorry, I tried to use markdown and it seems I forgot to attach a text to render the link over :(
[https://drive.google.com/file/d/1vVIsnSqq6340tCFG0wRDCSs-_Pb1bQf8/view?usp=sharing](https://drive.google.com/file/d/1vVIsnSqq6340tCFG0wRDCSs-_Pb1bQf8/view?usp=sharing)

**Comment by alexp-sssup** [comment]
@escalope The first problem I notice is that the application JAR includes a package (```org.xml```) which is already part of the runtime. Removing the package from the application archive seems to trigger a different error.

**Comment by alexp-sssup** [comment]
@escalope Question, at some point an XML attribute for the ```fill``` property is parsed. The attribute value is the empty string (""). Is this expected?

**Comment by escalope** [comment]
The package is automatically generated from maven through shade plugin(https://maven.apache.org/plugins/maven-shade-plugin/). I can exclude some packages, but, as you say, different errors may trigger. The shade plugin is supposed to create a self-contained bundle with exactly the classes needed to make the operation run.

I tried to remove the org.xml from the original jar and it still runs fine with native java. The same jar (without org.xml) through cheerpjfy returns more problems, but still also the same old ones. This is the one that seemed to me more related: 

> ingenias.exception.ParseException: Review XML compliance in file /rendererxml/CReceiveHelpINGENIASPanel.xml with content <?xml version="1.0" encoding="UTF-8" standalone="no" ?>
> <panel layout="BorderLayout(0,0)"  Background="white">
> <panel constraints="BorderLayout.NORTH" Background="white" layout="GridBagLayout">
> <htmllabel id="Id">
> <gridbagconstraints id="gbc_1" insets="0,0,0,0" gridx="0" gridy="0" fill="GridBagLayout.BOTH" anchor="GridBagLayout.CENTER"/>
> </htmllabel>
> </panel>> 
> <label Foreground="blue" icon="images/conditions/ReceiveHelp.png" 
> constraints="BorderLayout.CENTER" HorizontalAlignment="CENTER" />
> </panel>

If the XML is not parsed, there will be no graphics (I use SWIXML to transform XML into SWING graphical elements), and any posterior rendering will fail

**Comment by escalope** [comment]
Sorry, I did not see this before

> @escalope Question, at some point an XML attribute for the fill property is parsed. The attribute value is the empty string (""). Is this expected?

I cannot see where this empty string is. There should not be any empty "fill" values, anyway. There are many entities in each diagram. It is not possible that all of them have this empty fill attribute.

**Comment by escalope** [comment]
After clearing cache and trying the altered jar (without org.xml), it seems to behave better. There are still unexpected null pointers, but some icons are drawn in the diagram. I can't figure out why others not. Besides, this change leads to a irresponsive page when I start playing with the buttons to guess which ones are drawn and which ones are not. 

I created a log file with 
chrome --enable-logging --v=1 http://localhost:8080/index.html 
The result is this
[chrome_debug.log](https://github.com/leaningtech/cheerpj-meta/files/1851752/chrome_debug.log)

**Comment by alexp-sssup** [comment]
@escalope we may need to give you an experimental binary build to fix this problem. What is your platform of choice (Linux/Window/MacOS)?

**Comment by escalope** [comment]
Linux, please. amd64

**Comment by alexp-sssup** [comment]
@escalope please try rebuilding the application with this binary http://d3415aa6bfa4.leaningtech.com/cheerpj_linux_latest_20180406.tar.gz. We plan to release soon a 1.1 release that includes this fix.

**Comment by escalope** [comment]
I tested it and it looks way better

![image](https://user-images.githubusercontent.com/3056482/38420219-5647c9ae-39a3-11e8-988c-99c88d2facc8.png)

There are some weird messages  about not serializable objects. Can it be another bug?


[localhost-1523016148213.log](https://github.com/leaningtech/cheerpj-meta/files/1883830/localhost-1523016148213.log)

**Comment by alexp-sssup** [comment]
Unless you see any specific faulty behaviour I would assume that the message are not critical. I will close this bug, feel free to open new, more specific ones if the need arise.

**Comment by escalope** [comment]
OK, I will.

thanks for everything,
