### ISSUE TITLE
application.jar file is missing

### ISSUE THREAD

**Issue by changshin** [leaningtech/cheerpj-meta#3]
It is the first time I tried.
In Mac
I just downloaded the cheerpj_maxosx_preview_beta_1_20170925.tar.gz. and installed python3.
There is no applicartion.jar file.

 In Window.
py cheerjfy.py application.jar or rt.jar
or 
cheerjfy.py application.jar or rt.jar
The resullt is "usage cheerjpy.py file.jar"

Chang Shin

**Comment by changshin** [comment]
I see, If you provided the sample jar file, it is easy to test.
I tried to compile the rt.jar. it works on Mac. However It does not work on Window.

Chang Shin

**Comment by reportmill** [comment]
The rt.jar in the cheerpj_preview distribution is just the Java runtime jar (with all the standard runtime classes, like Object, String, List, etc.). I believe it’s the stripped version as well (there’s no real byte code in there).

Better to test with a jar from one of your own projects. :-)

By the way - you might want to join the CheerpJ developers google group <https://groups.google.com/forum/#!forum/cheerpj-developers>. That will probably be the best place to ask developer questions moving forward.

jeff
