### ISSUE TITLE
Not able to compile example jar

### ISSUE THREAD

**Issue by alpesh-shah** [leaningtech/cheerpj-meta#31]
I just downloaded cheerpj and following steps mentioned with example jar TextDemo.jar and getting below error. Don't know which file it is not able to find.  I created sample Applet too and tried to compile jar but same error. The applet and TextDemo.jar is running file if launch idependently.

D:\CheerpJ\cheerpj_1.0>py cheerpjfy.py TextDemo.jar
Compiling jar  TextDemo.jar
compiling components/TextDemo$1.class ...
compiling components/TextDemo.class ...
Traceback (most recent call last):
  File "cheerpjfy.py", line 414, in <module>
    runOnDir(tempDir);
  File "cheerpjfy.py", line 388, in runOnDir
    compileClassFiles(cheerpjCompiler, cheerpjClassPath, tempDir, jarFile, jarPath, jsOutput, option.isSplit);
  File "cheerpjfy.py", line 177, in compileClassFiles
    for f, compiled in executor.map(do_compile, jarFile.namelist()):
  File "C:\Users\alpesh.shah\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "C:\Users\alpesh.shah\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Users\alpesh.shah\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\alpesh.shah\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "cheerpjfy.py", line 143, in do_compile
    p = subprocess.Popen([cheerpj, "-precise-floats" if option.preciseFloats else "", "-llvm", "-llvm-exceptions", "-cp", cheerpjClassPath, f], cwd=jarUnpackPath,stdout=PIPE, stderr=STDOUT);
  File "C:\Users\alpesh.shah\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\alpesh.shah\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by alexp-sssup** [comment]
It seems to me that you have an outdated or corrupted version of the cheerpj zip package. What version of the package are you using? Can you share the content of the cheerpj_1.0 directory? (a screenshot will suffice)

**Comment by alpesh-shah** [comment]
Thanks for quick response, I downloaded latest package and got same issue again.
After detailed analysis I found that it was my anti virus tool considering cheerpj and cheerpj-strip as Malware with Insight Network Threat and deleting it based on risk WS.Reputation.1.  Detail about risk is mentioned at  https://www.symantec.com/security-center/writeup/2010-051308-1854-99?vid=4294919973

So I will now see how can I avoid that but it would be good if someone clarifies why this file coming under security scanner.

**Comment by alpesh-shah** [comment]
After putting these file in exception list of antivirus, now those files no longer getting deleted but getting below error

Compiling jar  TextDemo.jar
compiling components/TextDemo$1.class ...
Failure compiling components/TextDemo$1.class
command: D:\CheerpJ\cheerpj_1.0\bin\cheerpj "" -llvm -llvm-exceptions -cp C:\Users\ALPESH~1.SHA\AppData\Local\Temp\tmpau033u4t\rt.jar.dir\ components/TextDemo$1.class
Usage: D:\CheerpJ\cheerpj_1.0\bin\cheerpj <file.class or class>

**Comment by alexp-sssup** [comment]
We reported this false positive to Symantec. The second issue you mentioned is not reproducible on a clean system. Do you have the change the test on a different machine? At this stage I am not sure I we can further debug this issue.

**Comment by alexp-sssup** [comment]
Closing, please reopen if we still can't compile.
