### ISSUE TITLE
Java RMI

### ISSUE THREAD

**Issue by willishf** [leaningtech/cheerpj-meta#34]
Testing to see if RMI works error message below.

The Java application works as expected with a simple RMI call to pass a string and return that string with a message. Using port 5555 for the RMI server to listen for remote connection. Not sure what javascript library is being used for socket connections  that would allow RMI to work. From the error message not sure where to look. Will attach the server code and code fragment to make remote connection. If you want me to testing something please respond. 
[AnnotateROIServersrc.zip](https://github.com/leaningtech/cheerpj-meta/files/2128620/AnnotateROIServersrc.zip)

For the Java project that is converted to Javascript the following code works in Java when clicking a button. You would need to pull AnnotateRMIInterface from the attached source for the server. 

        try{
                  Registry reg = LocateRegistry.getRegistry("127.0.0.1", 5555);
                  AnnotateRMIInterface annotationRMI = (AnnotateRMIInterface) reg.lookup("AnnotateRMI");
                  System.out.println("Message:" + annotationRMI.getMessage("Hello"));
        }catch(Exception e){
            e.printStackTrace();
        } 

CheerpJ is initializing
cheerpOS.js:1264 java.rmi.ConnectIOException: Exception creating connection to: 127.0.0.1; nested exception is: 
	java.net.SocketException
cheerpOS.js:1264 

cheerpOS.js:1264 	at java.rmi.RemoteException(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at sun.rmi.transport.tcp.TCPChannel.createConnection(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at sun.rmi.transport.tcp.TCPChannel.newConnection(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at sun.rmi.server.UnicastRef.newCall(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at sun.rmi.registry.RegistryImpl_Stub.lookup(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at annotateroi.ROIPanel.jButtonRMITestActionPerformed(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at java.awt.Component.processMouseEvent(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at java.awt.Component.processEvent(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at java.awt.Container.processEvent(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at java.awt.Component.dispatchEventImpl(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at java.awt.Container.dispatchEventImpl(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at java.awt.Container.dispatchEventImpl(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at java.awt.EventQueue$3.run(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at java.awt.EventQueue$4.run(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at java.awt.EventDispatchThread.run(Unknown Source)
cheerpOS.js:1264 

cheerpj.js:1 assertion "
cheerpj.js:1 false
cheerpj.js:1 " failed: file "
cheerpj.js:1 CheerpJCompression.cpp
cheerpj.js:1 ", line 
cheerpj.js:1 354
cheerpj.js:1 static uint8_t CheerpJCompiler::CompressedState::getIdentifierBase64Value(char)
cheerpj.js:1 
cheerpOS.js:1264 Caused by: java.net.SocketException
cheerpOS.js:1264 

cheerpOS.js:1264 	at java.net.Socket.createImpl(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at java.net.Socket(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(Unknown Source)
cheerpOS.js:1264 

cheerpOS.js:1264 	... 26 more
cheerpOS.js:1264

**Comment by alexp-sssup** [comment]
Accessing the real network from the browser is not allowed. WebSockets, contrarily to their name, are not real sockets and can only connect to specially configured servers. We can engineer an ad-hoc solution for your case, please get in touch at info@leaningtech.com

**Comment by alexp-sssup** [comment]
Low level networking, including RMI, is now supported using Tailscale.

For more info: https://labs.leaningtech.com/cheerpj3/guides/Networking#generalized-networking
