### ISSUE TITLE
REST Jax-RS Jersey 2.5

### ISSUE THREAD

**Issue by willishf** [leaningtech/cheerpj-meta#36]
Put together a test case to see if it is possible to get REST client working using Jac-RS and Jersey. Unfortunately, it pulls in lots of external jar files. Worked to eliminate extra jar files. Attempting to process the required Jar files causes numerous failures and suspect the cheerpj transputing process is missing jar files needed to compile classes that are needed. 

The error messages during the crash are not descriptive so providing the output with the goal of understanding the problem or giving better details. Lots of failures but seems to fail on classes with the name Emitter in them so suspect a common problem. 

(base) C:\cheerpj_tutorial\AnnotateROI\lib>python c:/cheerpj_1.0/cheerpjfy.py --deps AnnotateROI.jar:cglib-2.2.0-b21.jar:guava-14.0.1.jar:hk2-api-2.2.0-b21.jar:hk2-locator-2.2.0-b21.jar:hk2-utils-2.2.0-b21.jar:javax.inject-2.2.0-b21.jar:javax.ws.rs-api-2.0.jar:jersey-client.jar:jersey-common.jar C:\cheerpj_tutorial\AnnotateROI\lib\cglib-2.2.0-b21.jar
Compiling jar  C:\cheerpj_tutorial\AnnotateROI\lib\cglib-2.2.0-b21.jar
compiling net/sf/cglib/util/ParallelSorter$ShortComparer.class ...
compiling net/sf/cglib/util/ParallelSorter$FloatComparer.class ...
compiling net/sf/cglib/util/ParallelSorter$ObjectComparer.class ...
compiling net/sf/cglib/util/ParallelSorter$ByteComparer.class ...
compiling net/sf/cglib/util/ParallelSorter$Generator.class ...
compiling net/sf/cglib/util/ParallelSorter$DoubleComparer.class ...
compiling net/sf/cglib/util/ParallelSorter$IntComparer.class ...
compiling net/sf/cglib/util/ParallelSorterEmitter.class ...
Failure compiling net/sf/cglib/util/ParallelSorterEmitter.class
command: c:\cheerpj_1.0\bin\cheerpj "" -llvm -llvm-exceptions -cp C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\rt.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\AnnotateROI.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\cglib-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\guava-14.0.1.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\hk2-api-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\hk2-locator-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\hk2-utils-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\javax.inject-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\javax.ws.rs-api-2.0.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\jersey-client.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\jersey-common.jar.dir\ net/sf/cglib/util/ParallelSorterEmitter.class

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

compiling net/sf/cglib/util/StringSwitcher.class ...
compiling net/sf/cglib/util/ParallelSorter$LongComparer.class ...
compiling net/sf/cglib/util/StringSwitcher$StringSwitcherKey.class ...
compiling net/sf/cglib/util/SorterTemplate.class ...
compiling net/sf/cglib/util/StringSwitcher$Generator.class ...
compiling net/sf/cglib/util/StringSwitcher$Generator$1.class ...
compiling net/sf/cglib/util/ParallelSorter.class ...
compiling net/sf/cglib/util/ParallelSorter$Comparer.class ...
compiling net/sf/cglib/util/ParallelSorter$ComparatorComparer.class ...
compiling net/sf/cglib/proxy/MethodInterceptorGenerator.class ...
compiling net/sf/cglib/proxy/Factory.class ...
compiling net/sf/cglib/proxy/InvocationHandler.class ...
compiling net/sf/cglib/proxy/MethodInterceptor.class ...
compiling net/sf/cglib/proxy/Mixin$Route.class ...
compiling net/sf/cglib/proxy/InterfaceMaker.class ...
compiling net/sf/cglib/proxy/Enhancer$2.class ...
compiling net/sf/cglib/proxy/LazyLoaderGenerator.class ...
compiling net/sf/cglib/proxy/MethodProxy$1.class ...
compiling net/sf/cglib/proxy/Enhancer$EnhancerKey.class ...
compiling net/sf/cglib/proxy/CallbackGenerator.class ...
compiling net/sf/cglib/proxy/NoOp$1.class ...
compiling net/sf/cglib/proxy/Mixin.class ...
compiling net/sf/cglib/proxy/Enhancer$3.class ...
compiling net/sf/cglib/proxy/Proxy$1.class ...
compiling net/sf/cglib/proxy/Enhancer.class ...
compiling net/sf/cglib/proxy/MixinEmitter.class ...
Failure compiling net/sf/cglib/proxy/MixinEmitter.class
command: c:\cheerpj_1.0\bin\cheerpj "" -llvm -llvm-exceptions -cp C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\rt.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\AnnotateROI.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\cglib-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\guava-14.0.1.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\hk2-api-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\hk2-locator-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\hk2-utils-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\javax.inject-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\javax.ws.rs-api-2.0.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\jersey-client.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\jersey-common.jar.dir\ net/sf/cglib/proxy/MixinEmitter.class

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

compiling net/sf/cglib/proxy/MethodProxy$FastClassInfo.class ...
compiling net/sf/cglib/proxy/Mixin$Generator.class ...
compiling net/sf/cglib/proxy/Enhancer$1.class ...
compiling net/sf/cglib/proxy/MethodProxy.class ...
compiling net/sf/cglib/proxy/Enhancer$6.class ...
compiling net/sf/cglib/proxy/CallbackFilter.class ...
compiling net/sf/cglib/proxy/MethodProxy$CreateInfo.class ...
compiling net/sf/cglib/proxy/DispatcherGenerator.class ...
compiling net/sf/cglib/proxy/FixedValue.class ...
compiling net/sf/cglib/proxy/MixinEverythingEmitter.class ...
Failure compiling net/sf/cglib/proxy/MixinEverythingEmitter.class
command: c:\cheerpj_1.0\bin\cheerpj "" -llvm -llvm-exceptions -cp C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\rt.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\AnnotateROI.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\cglib-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\guava-14.0.1.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\hk2-api-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\hk2-locator-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\hk2-utils-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\javax.inject-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\javax.ws.rs-api-2.0.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\jersey-client.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\jersey-common.jar.dir\ net/sf/cglib/proxy/MixinEverythingEmitter.class

compiling net/sf/cglib/proxy/NoOp.class ...
compiling net/sf/cglib/proxy/CallbackHelper.class ...
compiling net/sf/cglib/proxy/MethodInterceptorGenerator$1.class ...
compiling net/sf/cglib/proxy/MixinBeanEmitter.class ...
Failure compiling net/sf/cglib/proxy/MixinBeanEmitter.class
command: c:\cheerpj_1.0\bin\cheerpj "" -llvm -llvm-exceptions -cp C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\rt.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\AnnotateROI.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\cglib-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\guava-14.0.1.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\hk2-api-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\hk2-locator-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\hk2-utils-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\javax.inject-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\javax.ws.rs-api-2.0.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\jersey-client.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\jersey-common.jar.dir\ net/sf/cglib/proxy/MixinBeanEmitter.class

compiling net/sf/cglib/proxy/UndeclaredThrowableException.class ...
compiling net/sf/cglib/proxy/Dispatcher.class ...
compiling net/sf/cglib/proxy/Proxy$ProxyImpl.class ...
compiling net/sf/cglib/proxy/FixedValueGenerator.class ...
compiling net/sf/cglib/proxy/ProxyRefDispatcher.class ...
compiling net/sf/cglib/proxy/Enhancer$4.class ...
compiling net/sf/cglib/proxy/InvocationHandlerGenerator.class ...
compiling net/sf/cglib/proxy/Mixin$MixinKey.class ...
compiling net/sf/cglib/proxy/MethodInterceptorGenerator$2.class ...
compiling net/sf/cglib/proxy/CallbackGenerator$Context.class ...
compiling net/sf/cglib/proxy/NoOpGenerator.class ...
compiling net/sf/cglib/proxy/Proxy.class ...
compiling net/sf/cglib/proxy/CallbackInfo.class ...
compiling net/sf/cglib/proxy/Enhancer$5.class ...
compiling net/sf/cglib/proxy/LazyLoader.class ...
compiling net/sf/cglib/proxy/Callback.class ...
compiling net/sf/cglib/core/KeyFactory$2.class ...
compiling net/sf/cglib/core/EmitUtils$8.class ...
compiling net/sf/cglib/core/ReflectUtils$4.class ...
compiling net/sf/cglib/core/Signature.class ...
compiling net/sf/cglib/core/ClassesKey$Key.class ...
compiling net/sf/cglib/core/EmitUtils$4.class ...
compiling net/sf/cglib/core/EmitUtils$10.class ...
compiling net/sf/cglib/core/ClassNameReader$1.class ...
Failure compiling net/sf/cglib/core/ClassNameReader$1.class
command: c:\cheerpj_1.0\bin\cheerpj "" -llvm -llvm-exceptions -cp C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\rt.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\AnnotateROI.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\cglib-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\guava-14.0.1.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\hk2-api-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\hk2-locator-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\hk2-utils-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\javax.inject-2.2.0-b21.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\javax.ws.rs-api-2.0.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\jersey-client.jar.dir\:C:\Users\SCOOTE~1\AppData\Local\Temp\tmps6jog_zr\jersey-common.jar.dir\ net/sf/cglib/core/ClassNameReader$1.class

**Comment by alexp-sssup** [comment]
A few failures are not necessarily fatal. All required classes are found, otherwise you would see messages like ```Could not open class ...```. This kind of crashes can happen if the versions of the various JARs are not compatible, for example if a required static field is not actually available in its class.

If the same JARs can execute correctly with native java, it is highly probable that these failures are not a problem.

**Comment by willishf** [comment]
The python script is crashing as indicated by the following error message. I have a batch script that runs for each jar file. When it crashes you get a microsoft error box that pops up.

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by alexp-sssup** [comment]
We are aware that Windows have this very annoying behaviour of showing popups on application errors, close the popups to let the cheerpjfy script finish. Then you can test if the application is working.

It is not possible for us to debug the specific crashes without the having access to the all the JARs, if you can upload somewhere an archive with all of them we can take a look at the root problem, but most probably the application will just work notwithstanding these few crashes.

**Comment by willishf** [comment]
I have uploaded the jar files that get pulled in with Jax and Jersey framework to do REST client. Adds lots of jar files so being able to reduce how much needs to be loaded would be nice. In the directory is the batch file I put together to iterate through each jar file per the example provided on your website. 

The nature of the error messages it did not complete the compiling of a specific class which would suggest not ideal for expecting it to work.

Failure compiling net/sf/cglib/transform/AbstractTransformTask.class
Failure compiling net/sf/cglib/transform/AbstractProcessTask.class


https://drive.google.com/open?id=1OQgZV_tCmBhYvlMgskl-K8lHk-YsK8u0

**Comment by willishf** [comment]
It has been a long time since doing any single jar/obfuscation work. Played around with ProGuard and didn't seem like it was focused on removing extra classes. 

Any recommendations for a tool that does a good job of creating a single jar with only the classes that are needed? One of the dependencies for the Jersy frawework is eclipselink which is 8MB jar file that grows to a 44mb javascript file. 

Would be nice to have a repository of popular pre-compliled/javascript jar files that could be downloaded. The transputing takes some time.

Would also be helpful to have an index file of all classes and a corresponding jar file to find the file as part of the application class. This way you could do lazy downloading of the jar.js files when and if needed.

**Comment by alexp-sssup** [comment]
I am afraid I don't know of any specific tool, but I have seen monolithic JARs containing all their dependencies, so I think there should be something available.

To reduce compilation time you can use the parallel build option ```-j N``` of cheerpjfy.py. You can also use the ```--work-dir``` option to cache the unmodified files instead of rebuilding everything from scratch.

jar.js files are already lazily downloaded, jar files on the other hand are downloaded to resolve the classes. To reduce download size jar files can be "packed" by cheerpjfy.py https://github.com/leaningtech/cheerpj-meta/wiki/Startup-time-optimization#reduce-the-size-of-the-jar-file

**Comment by willishf** [comment]
Finally got the files compiled and using the following to load multiple jars and getting a non-descript error. The path is correct loading from a deployed web app. 

Uncaught Error: Abort called
    at lK (cjrtnc.leaningtech.com/latest/icu.js:1)
    at aP (cjrtnc.leaningtech.com/latest/icu.js:1)
    at Object.eval [as func] (eval at buildContinuations (loader.js:118), <anonymous>:3:254)
    at runContinuationStack (loader.js:378)
    at cheerpjSchedule (loader.js:1028)
    at IFrameProxyDownloader.dl.onload (cheerpOS.js:375)
    at MessagePort.ipfMessage (loader.js:3175)




<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>CheerpJ test</title>
    <script src="https://cjrtnc.leaningtech.com/latest/loader.js"></script>
  </head>
  <body>
  </body>
  <script>
      cheerpjInit();
      cjCall("java.lang.System", "setProperty", "java.protocol.handler.pkgs", "com.leaningtech.handlers");
      cheerpjCreateDisplay(1200,1000);
      cheerpjRunMain("annotateroi.ROIPanel","AnnotateROIServer/AnnotateROI.jar:AnnotateROIServer/asm-all-repackaged-2.2.0-b21.jar:AnnotateROIServer/cglib-2.2.0-b21.jar:AnnotateROIServer/eclipselink.jar:AnnotateROIServer/guava-14.0.1.jar:AnnotateROIServer/hk2-api-2.2.0-b21.jar:AnnotateROIServer/hk2-locator-2.2.0-b21.jar:AnnotateROIServer/hk2-utils-2.2.0-b21.jar:AnnotateROIServer/javax.annotation-api-1.2.jar:AnnotateROIServer/javax.inject-2.2.0-b21.jar:AnnotateROIServer/javax.servlet-api-3.0.1.jar:AnnotateROIServer/javax.ws.rs-api-2.0.jar:AnnotateROIServer/jaxb-api-2.2.7.jar:AnnotateROIServer/jersey-client.jar:AnnotateROIServer/jersey-common.jar:AnnotateROIServer/jersey-container-servlet-core.jar:AnnotateROIServer/jersey-container-servlet.jar:AnnotateROIServer/jersey-entity-filtering-2.5.1.jar:AnnotateROIServer/jersey-media-moxy-2.5.1.jar:AnnotateROIServer/jersey-server.jar:AnnotateROIServer/org.osgi.core-4.2.0.jar:AnnotateROIServer/osgi-resource-locator-1.0.1.jar:AnnotateROIServer/persistence-api-1.0.jar:AnnotateROIServer/validation-api-1.1.0.Final.jar"); 
  </script>
</html>

**Comment by willishf** [comment]
Cleared the cache and the problem went away.

Continued testing and get error messages where it can't find the jar files located in a lib directory. I don't have any reference to a lib directory as a I put the jar and jar.js files in the root directory. 

This is example of the error message returned for each jar file where not sure why lib is being referenced. 

cheerpOS.js:220 HEAD http://localhost:8084/AnnotateROIServer/lib/javax.ws.rs-api-2.0.jar 404 (Not Found)

**Comment by willishf** [comment]
Copy the jar and jar.js files to lib directory allowed for code testing. Clicking on the button that calls the method for the JAX REST set of libraries resulted in a very long load time(button stuck) which is understandable given the number of jar files for the framework. Results in throwing an exception for missing class file and related to the compiling step that throws lots of errors. Good news making progress where unfortunately pulling in these external frameworks and tracking down all dependencies to compile properly is not trivial.

**Comment by willishf** [comment]
This missing class org.glassfish.jersey.internal.runtimedelegateimpl appears to be a common problem with various solutions depending on version of Java etc. 

https://stackoverflow.com/questions/30316829/classnotfoundexception-org-glassfish-jersey-internal-runtimedelegateimpl-cannot

Not sure what the next step is to resolve the dependency in the context of Cheerpj.

**Comment by alexp-sssup** [comment]
I am missing something here. Glassfish is a Java EE application server. I think that you want to compile a Java client that uses REST to communicate with glassfish (or another Java EE server).

You most certainly do not need that class.

**Comment by willishf** [comment]
Using Java SE jdk1.8.0_161 as the client and code works as expected running from Netbeans 8.  If you search on that specific missing classes you will see many have the same problem using Java. This is an example discussion on the differences between Eclipse, InteliJ and Java 6 vs Java 8. https://github.com/jimmoores/quandl4j/issues/4 
https://stackoverflow.com/questions/19452887/org-glassfish-jersey-internal-runtimedelegateimpl-not-found/20258438

It could be working in Netbeans because something on the classpath is resolving/setting the missing class. 

Given the long load times of the classes and the headaches of an overly complex framework that isn't absolutely needed will be focused on using a simple/clean REST framework with JSON support someone put together for android. 

Was trying to use the Jersey REST framework as Netbeans will auto-generate code for REST services which saves time on application development. 

Any Java application worth porting to web browser is going to have JDBC, RMI or REST dependencies that consume lots of external frameworks so these problems are relevant to the adoption of Cheerpj.

**Comment by alexp-sssup** [comment]
There are multiple commercial users already deploying CheerpJ in production with REST based applets, so we know that CheerpJ is robust enough to handle these scenarios.

I suspect that netbeans is silently adding something on the classpath. You should try to actually run the application from the command line using plain java. From the same directory where you have your HTML page try:

```
java -cp AnnotateROIServer/AnnotateROI.jar:AnnotateROIServer/asm-all-repackaged-2.2.0-b21.jar:AnnotateROIServer/cglib-2.2.0-b21.jar:AnnotateROIServer/eclipselink.jar:AnnotateROIServer/guava-14.0.1.jar:AnnotateROIServer/hk2-api-2.2.0-b21.jar:AnnotateROIServer/hk2-locator-2.2.0-b21.jar:AnnotateROIServer/hk2-utils-2.2.0-b21.jar:AnnotateROIServer/javax.annotation-api-1.2.jar:AnnotateROIServer/javax.inject-2.2.0-b21.jar:AnnotateROIServer/javax.servlet-api-3.0.1.jar:AnnotateROIServer/javax.ws.rs-api-2.0.jar:AnnotateROIServer/jaxb-api-2.2.7.jar:AnnotateROIServer/jersey-client.jar:AnnotateROIServer/jersey-common.jar:AnnotateROIServer/jersey-container-servlet-core.jar:AnnotateROIServer/jersey-container-servlet.jar:AnnotateROIServer/jersey-entity-filtering-2.5.1.jar:AnnotateROIServer/jersey-media-moxy-2.5.1.jar:AnnotateROIServer/jersey-server.jar:AnnotateROIServer/org.osgi.core-4.2.0.jar:AnnotateROIServer/osgi-resource-locator-1.0.1.jar:AnnotateROIServer/persistence-api-1.0.jar:AnnotateROIServer/validation-api-1.1.0.Final.jar annotateroi.ROIPanel
```

This command is equivalent to the ```cheerpjRunMain``` call in the HTML file.

**Comment by willishf** [comment]
Runs as expected(no errors and get the desired result) with Java 8 using the -cp jars on the classpath. Could be an OpenJDK implementation difference if it is a Java VM dependency.

For the commercial clients do you know what REST framework they are using?
 

Tested under Java 10 and entirely different set and larger number of classes not found which is expected. 

Ran the following jcmd 6836 VM.system_properties where 6836 is the PID of the running application to see if any code had set a system property which has been discussed by others having problems with that same missing class. Did not see anything in the system.properties dump that would indicate runtime behavior had been altered by a calling class in the JAX framework. 

The error could be caused because one of the classes that through the "error" during transputing is required. 

If you are curious and have the ability to properly debug the javascript code you can run the application and press Test 3 button that would run the code in question where you don't need the server. An error of can't find the server would be progress.  https://drive.google.com/open?id=1OQgZV_tCmBhYvlMgskl-K8lHk-YsK8u0

I can try rebuilding with the missing "Ant" jar and see if that makes a difference. Hoping you have the ability to debug the javascript code where the error is being thrown and possibly look over the corresponding java source for that class for a clue.

**Comment by alexp-sssup** [comment]
I discovered several things

1) There is no "Test 3" button in the application, neither in native or when running with CheerpJ
2) Do you get any graphical output in CheerpJ? The HTML page you showed above is broken, please take a look at https://github.com/leaningtech/cheerpj-meta/wiki/Getting-started#basic-html-page-for-testing for an example of how a basic HTML page should look like.
3) When trying "Test 2" the real problem is not that "org.glassfish.jersey.internal.RuntimeDelegateImpl" is missing, but a NullPointerException that happens before. I am still investigating why this happens.

**Comment by willishf** [comment]
Let me make sure I upload the application jar/js file from the application
server and the correct HTML file. I pulled from the build directory and it
was probably was an intermediate version from testing.

**Comment by willishf** [comment]
Just reviewed and it is the Test2 button. Test is a simple http get version
of a REST call. Test1 is using the lightweight android REST/json framework.
Test2 was using the JAX-RS framework and is the 3rd button. I uploaded the
html file and the jar/js application files from the application server to
the google drive link. The path dependency in the html is because I have a
WEB application deployed as AnnotateROIServer loading the files. When
trying to use relative path it couldn't find the jar files so added in the
application path which got rid of 404 errors but not ideal.  Then got a
weird behavior that it was throwing 404 errors looking for the files in a
lib directory under the application server so had to duplicate the files in
that directory to make it happy. I haven't spent any time trying to figure
out is cheerpj is expecting the files in a particular directory from teh
python app example.

**Comment by alexp-sssup** [comment]
We identified and fixed a minor issue related to reflection/annotation support. Please clear your browser cache and try again, I can now see that an HTTP request is send via XHR to a local server.

**Comment by willishf** [comment]
Excellent!!!!
