### ISSUE TITLE
HttpURLConnection errors

### ISSUE THREAD

**Issue by willishf** [leaningtech/cheerpj-meta#37]
Working on a solution to get REST functionality so that the cheerpj application can communicate with the web server. The following code can be used for testing where substitute a URL of your choice. The Java application version works as expected. When I run this code get the following errors. I am assuming that HttpURLConnection was not mapped to the corresponding api in Javascript. 

At this point, I can not move forward with cheerpj as it does not appear you can communicate with a web server. Having an implementation that has a read-only file system from web server and a local file system as a browser database does not lend itself to software that can do anything useful.

Would appreciate some guidance/pointers on other options to explore. At a minimum would expect HttpURLConnection to work and assume it wasn't tested. 

java.net.SocketException
cheerpOS.js:1370 

cheerpOS.js:1370 	at java.net.Socket.createImpl(Unknown Source)
cheerpOS.js:1370 

cheerpOS.js:1370 	at java.net.Socket.connect(Unknown Source)
cheerpOS.js:1370 

cheerpOS.js:1370 	at sun.net.NetworkClient.doConnect(Unknown Source)
cheerpOS.js:1370 

cheerpOS.js:1370 	at sun.net.www.http.HttpClient.openServer(Unknown Source)
cheerpOS.js:1370 

cheerpOS.js:1370 	at sun.net.www.http.HttpClient.openServer(Unknown Source)
cheerpOS.js:1370 

cheerpOS.js:1370 	at sun.net.www.http.HttpClient.New(Unknown Source)
cheerpOS.js:1370 

cheerpOS.js:1370 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
cheerpOS.js:1370 

cheerpOS.js:1370 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
cheerpOS.js:1370 

cheerpOS.js:1370 	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
cheerpOS.js:1370 

cheerpOS.js:1370 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
cheerpOS.js:1370 

cheerpOS.js:1370 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
cheerpOS.js:1370 

cheerpOS.js:1370 	at annotateroi.client.GetTest.getAnnotations(Unknown Source)
cheerpOS.js:1370 

 public static void getAnnotations() {
        HttpURLConnection connection = null;
        BufferedReader reader = null;
        String retVal = null;
        try {
            URL resetEndpoint = new URL("http://localhost:8084/AnnotateROIServer/webresources/image/getAnnotations?id=452&zip=1234");
            connection = (HttpURLConnection) resetEndpoint.openConnection();
            //Set request method to GET as required from the API
            connection.setRequestMethod("GET");

            // Read the response
            reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            StringBuilder jsonSb = new StringBuilder();
            String line = null;
            while ((line = reader.readLine()) != null) {
                jsonSb.append(line);
            }
            retVal = jsonSb.toString();

            // print out the json response
            System.out.println(retVal);

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // Clean up
            if (reader != null) {
                try {
                    reader.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            if (connection != null) {
                connection.disconnect();
            }
        }

    }

**Comment by alexp-sssup** [comment]
CheerpJ includes a XHR based HttpURLConnection, to use it you need to enable it by setting the ```java.protocol.handler.pkgs``` property as in the following example:

```
cheerpjInit();
cjCall("java.lang.System", "setProperty", "java.protocol.handler.pkgs", "com.leaningtech.handlers");
cheerpjRunMain("Test","");
```

CheerpJ handlers are enabled by default when using CheerpJ to run applets, for applications you need to run setProperty manually before starting the application.

**Comment by alexp-sssup** [comment]
We have also documented this has part of out FAQs for future reference: https://github.com/leaningtech/cheerpj-meta/wiki/Frequently-Asked-Questions#my-java-application-needs-to-get-data-over-the-network-but-i-only-get-socketexceptions
