### ISSUE TITLE
HTTP request to https://cjrtnc.leaningtech.com returns 403

### ISSUE THREAD

**Issue by gtamas** [leaningtech/cheerpj-meta#38]
Hi

I'm trying to run the generated app in the browser (Chrome, latest). It works fine, but at some point it performs this HTTP request:

https://cjrtnc.leaningtech.com/latest/cheerpj/lib/cmm/

... which returns 403 so the process fails. 

Any suggestions on how to fix this?

**Comment by alexp-sssup** [comment]
The 403 is most probably not a problem. HTTP errors are correctly handled by the filesystem backend. In this case a 403 error on a directory will be interpreted as "the directory exists, but indexing is disabled". This is a supported and normal behaviour.

To understand the actual problem you need to provide us with more information.
