### ISSUE TITLE
High CPU usage at idle

### ISSUE THREAD

**Issue by willishf** [leaningtech/cheerpj-meta#43]
Running a Swing app compiled with cheerpj and get high cpu usage with nothing happening in the app. Basically when I run the app and leave it open in chrome my laptop fan turns on. This idle app is taking up 16% of CPU and not doing anything waiting for a swing event. 

Anything that I should test to see what is busy in javascript code?

![image](https://user-images.githubusercontent.com/4054430/44008152-16fe4e1e-9e6e-11e8-98f7-ffe6e94717fd.png)

**Comment by alexp-sssup** [comment]
If something is running then the application is not truly idle. There might be background threads polling on some condition for example. Breaking using the debugger could give you a rough idea of what is being run. All the names of the methods are compressed and mangled, but you can decode them from the console using the ```cheerpjDecompressSymbol(funcName)``` command. The argument should be the name as shown on the debugger stacktrace excluding the first ```_``` character.

**Comment by alexp-sssup** [comment]
Closing due to lack of information.
