### ISSUE TITLE
Oracle Forms conversion

### ISSUE THREAD

**Issue by vasso123** [leaningtech/cheerpj-meta#44]
Couldn't find any info about support for conversion of Oracle Forms using Cheerpj.
As Oracle Forms are basically applets, then as I understand it should be possible to convert them?

**Comment by alexp-sssup** [comment]
We have no specific information about Oracle Forms, but the general rule is that any Java application and applet can be converted. CheerpJ is used on multiple large scale commercial applets already.

**Comment by vasso123** [comment]
For example I tried running this demo app:
https://forms-demo.com/forms/webutil/exit_ie.html
Using Chrome and Cheerpj extension, without success.

**Comment by alexp-sssup** [comment]
The demo you mentioned (available here: https://forms-demo.com/forms/frmservlet?config=DEMO0001) is now fixed in the new version of CheerpJ Applet Runner. Please make sure the extension is at version 3.4 and try again.
