### ISSUE TITLE
How to call `cjNew` on `CheerpJWorker`?

### ISSUE THREAD

**Issue by vonwenckstern** [leaningtech/cheerpj-meta#52]
The following code works without web worker:
```
 cheerpjInit()
 cheerpjRunMain("ocl.cli.OCLCDTool", "/app/OCL/ocl.jar");
		  
 function parse() {
   var parser = cjNew("ocl.monticoreocl.ocl._parser.OCLParser");

  var oclString = "context Auction a inv: a.participants.size > 0";
  cjCall(parser, "parse_String", oclString).then(
   function(ast) {
     console.log(ast);					
   }
  );
 }
```

however how do we call the same function with web worker, because
```
var w = new CheerpJWorker();
w.cheerpjInit().then(function(e) { console.log("CheerpJWorker is ready"); });
w.cheerpjRunMain("ocl.cli.OCLCDTool", "/app/OCL/ocl.jar");
		  
function parse() {
   var parser = cjNew("ocl.monticoreocl.ocl._parser.OCLParser");
   var oclString = "context Auction a inv: a.participants.size > 0";
   w.cjCall(parser, "parse_String", oclString).then(
  function(ast) {
    console.log(ast);					
 }
);
}
```
does not work, it causes the error `Cannot read property '0' of null`:
![image](https://user-images.githubusercontent.com/30497492/50132399-48661180-0287-11e9-9e35-be6d7ff6e4fc.png)

and **`var parser = w.cjNew("ocl.monticoreocl.ocl._parser.OCLParser");`** causes the error `w.cjNew is not a function`.

**Comment by vonwenckstern** [comment]
we are using https://cjrt.leaningtech.com/1.0/loader.js, because the other releases do not work for us (cf. #50 and #51)

**Comment by alexp-sssup** [comment]
cjNew on Workers was not support with CheerpJ 1.0

Please do not use older versions of CheerpJ since we cannot provide support for them
