### ISSUE TITLE
internal error when loading a JAR

### ISSUE THREAD

**Issue by vonwenckstern** [leaningtech/cheerpj-meta#54]
When loading our OCL.jar we receive the following error:
```
Reporting error: Unhandled exception N4java4lang20NullPointerException/_m4_08Shutdown5halt0EIEV,_m4V08Shutdown4haltEIEV,_m4V08Shutdown4exitEIEV,_m4F07Runtime4exitEIEV,_c4FbMlG9cq$a_sCunE5rj0CiXYdruoqGt0K3c9RCF7rKJfqWcHe9hSgd9JmAqcHWK3l,_c4FbMlG9cq$a_sCunE5rjSDiXYdruTUWbHGIwZqPdWGjasJ3SOe9hS3c9BCo3cGKeE,internal
```

Can it be that the error occurs, because we execute two main methods of two different jars? (https://github.com/EmbeddedMontiArc/webspace/blob/master/OCL/resources/js/cheerpjWrite.js#L32, and https://github.com/EmbeddedMontiArc/webspace/blob/master/OCL/resources/js/cheerpjWrite.js#L36)

You can reproduce the error by: 

1. opening: https://embeddedmontiarc.github.io/webspace/OCL/fail.html
2. and then clicking at the play sign: 
![image](https://user-images.githubusercontent.com/30497492/50195810-f386d180-0340-11e9-8256-26f2a947f686.png)

**Comment by alexp-sssup** [comment]
Using cheerpjRunMain multiple times is supported but you need to have the same list of JARs on both calls.
