### ISSUE TITLE
Demo source difficult to find

### ISSUE THREAD

**Issue by juckele** [leaningtech/cheerpj-meta#56]
Looking at some of the demos like https://cheerpjdemos.leaningtech.com/iTextDemo.html and I've been unable to find the source in the tutorial / getting started docs. A link to the source of the demos would improve the existing documentation substantially.

**Comment by alexp-sssup** [comment]
Information about the demos has been added to the wiki
https://github.com/leaningtech/cheerpj-meta/wiki/Demos
