### ISSUE TITLE
Impossible to use pack-jar option

### ISSUE THREAD

**Issue by maxiplay** [leaningtech/cheerpj-meta#57]
Hello !

You do a very great work !
I am testing cheerpj to use the LanguageTool Spellchecker in browser with your tool. (https://languagetool.org/)
https://github.com/languagetool-org/languagetool/issues/1323

I Created a repository for my test (branch cheerpj) => https://github.com/maxiplay/LanguageTool-WebAssembly 

The compilation of the small test project work but the compiled project is heavy weight so I try to follow your recommandations. => https://github.com/leaningtech/cheerpj-meta/wiki/Startup-time-optimization

I have problems using the pack-jar option.

```
compiling opennlp/tools/util/model/PropertiesSerializer.class ...
compiling opennlp/tools/util/model/SerializableArtifact.class ...
compiling opennlp/tools/util/model/UncloseableInputStream.class ...
Packing JAR target/ltwa-1.0-SNAPSHOT-jar-with-dependencies.jar
Traceback (most recent call last):
  File "cheerpj_1.3/cheerpjfy.py", line 420, in <module>
    runOnDir(tempDir);
  File "cheerpj_1.3/cheerpjfy.py", line 398, in runOnDir
    makePackedJar(jarFile, jarPath, option.packJar, packClasses);
  File "cheerpj_1.3/cheerpjfy.py", line 317, in makePackedJar
    p = subprocess.Popen(["pack200", "--method-attribute=Code=strip", "--field-attribute=ConstantValue=strip", "-G", "-r", packedJarPath, jarPath]);
  File "C:\Users\Maxime\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Maxime\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Le fichier sp▒cifi▒ est introuvable

```

I don"t understand if I must provide a new name for the packed jar or give the same name that jar to compile.
I tried the two options but it failed. I tried also to put a absolute path but nothing work.
Perhaps a problem with python on Windows 10 ?

`py cheerpj_1.3/cheerpjfy.py --pack-jar=ltwa-packed.jar -j 10 target/ltwa-1.0-SNAPSHOT-jar-with-dependencies.jar`

**Comment by alexp-sssup** [comment]
The ```pack200``` tool which comes as part of the standard OpenJDK is not available in the path. You need to install OpenJDK manually and try again.

**Comment by maxiplay** [comment]
Ok that's it. Thx :)
