### ISSUE TITLE
LanguageTool - Compilation failed for certains class and runtime exception

### ISSUE THREAD

**Issue by maxiplay** [leaningtech/cheerpj-meta#58]
I am testing cheerpj to use the LanguageTool Spellchecker in browser with your tool. (https://languagetool.org/)
languagetool-org/languagetool#1323

I Created a repository for my test (branch cheerpj) => https://github.com/maxiplay/LanguageTool-WebAssembly

You can test with the master branch.

English version of the spellcheck compile except other file but the text spellching worked.

French Version get a runtime exception during the spellchecking and has 2 compilation problems

![capture](https://user-images.githubusercontent.com/8363127/50548511-6865df80-0c4e-11e9-9877-cc8978f80b7e.PNG)

Compilation : 

Failure compiling META-INF/versions/9/javax/xml/bind/ModuleUtil.class
command: C:\Users\Maxime\Documents\writecontrol\LanguageTool-WebAssembly\cheerpj_1.3\bin\cheerpj "" -llvm -llvm-exceptions -cp C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\rt.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\language-fr-4.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\languagetool-core-4.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\commons-lang3-3.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\guava-21.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jna-4.4.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\morfologik-fsa-2.1.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\morfologik-fsa-builders-2.1.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\morfologik-speller-2.1.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\morfologik-stemming-2.1.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\hppc-0.7.2.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\segment-2.0.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\commons-logging-1.1.1.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\language-detector-0.6.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jsonic-1.2.11.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\annotations-12.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\lucene-core-5.5.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\lucene-backward-codecs-5.5.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\berkeleylm-1.1.2.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jackson-databind-2.9.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jackson-annotations-2.9.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jackson-core-2.9.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\unit-api-1.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\indriya-1.2.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\uom-lib-common-1.1.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jaxb-api-2.3.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jaxb-runtime-2.3.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jaxb-core-2.3.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\txw2-2.3.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\istack-commons-runtime-3.0.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\stax-ex-1.7.8.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\FastInfoset-1.2.13.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\javax.activation-api-1.2.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\slf4j-api-1.7.25.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\xgboost-predictor-0.3.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jafama-2.1.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\commons-csv-1.6.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\hunspell-native-libs-2.9.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\annotations-12.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\berkeleylm-1.1.2.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\commons-csv-1.6.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\commons-lang3-3.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\commons-logging-1.1.1.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\FastInfoset-1.2.13.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\guava-21.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\hppc-0.7.2.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\hunspell-native-libs-2.9.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\indriya-1.2.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\istack-commons-runtime-3.0.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jackson-annotations-2.9.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jackson-core-2.9.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jackson-databind-2.9.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jafama-2.1.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\javax.activation-api-1.2.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\javax.servlet-api-3.1.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jaxb-api-2.3.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jaxb-core-2.3.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jaxb-runtime-2.3.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jna-4.4.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jsonic-1.2.11.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\language-detector-0.6.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\language-fr-4.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\languagetool-core-4.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\lucene-backward-codecs-5.5.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\lucene-core-5.5.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\morfologik-fsa-2.1.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\morfologik-fsa-builders-2.1.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\morfologik-speller-2.1.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\morfologik-stemming-2.1.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\segment-2.0.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\slf4j-api-1.7.25.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\stax-ex-1.7.8.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\txw2-2.3.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\unit-api-1.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\uom-lib-common-1.1.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\xgboost-predictor-0.3.0.jar.dir\ META-INF/versions/9/javax/xml/bind/ModuleUtil.class
Loading class META-INF/versions/9/javax/xml/bind/ModuleUtil and dependencies

Could not open class java/lang/Module

Could not open class java/lang/invoke/StringConcatFactory

Unsupported LLVM generation for opcode ba

In function getClassesFromContextPath

SUPPORT CONSTANT 8Assertion failed!

Program: C:\Users\Maxime\Documents\writecontrol\LanguageTool-WebAssembly\cheerpj_1.3\bin\cheerpj

File: CheerpJCompilerMethod.cpp, Line 2241

Expression: false
`

And

`Failure compiling module-info.class
command: C:\Users\Maxime\Documents\writecontrol\LanguageTool-WebAssembly\cheerpj_1.3\bin\cheerpj "" -llvm -llvm-exceptions -cp C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\rt.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\language-fr-4.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\languagetool-core-4.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\commons-lang3-3.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\guava-21.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jna-4.4.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\morfologik-fsa-2.1.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\morfologik-fsa-builders-2.1.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\morfologik-speller-2.1.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\morfologik-stemming-2.1.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\hppc-0.7.2.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\segment-2.0.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\commons-logging-1.1.1.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\language-detector-0.6.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jsonic-1.2.11.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\annotations-12.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\lucene-core-5.5.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\lucene-backward-codecs-5.5.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\berkeleylm-1.1.2.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jackson-databind-2.9.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jackson-annotations-2.9.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jackson-core-2.9.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\unit-api-1.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\indriya-1.2.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\uom-lib-common-1.1.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jaxb-api-2.3.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jaxb-runtime-2.3.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jaxb-core-2.3.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\txw2-2.3.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\istack-commons-runtime-3.0.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\stax-ex-1.7.8.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\FastInfoset-1.2.13.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\javax.activation-api-1.2.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\slf4j-api-1.7.25.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\xgboost-predictor-0.3.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jafama-2.1.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\commons-csv-1.6.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\hunspell-native-libs-2.9.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\annotations-12.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\berkeleylm-1.1.2.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\commons-csv-1.6.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\commons-lang3-3.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\commons-logging-1.1.1.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\FastInfoset-1.2.13.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\guava-21.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\hppc-0.7.2.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\hunspell-native-libs-2.9.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\indriya-1.2.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\istack-commons-runtime-3.0.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jackson-annotations-2.9.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jackson-core-2.9.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jackson-databind-2.9.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jafama-2.1.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\javax.activation-api-1.2.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\javax.servlet-api-3.1.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jaxb-api-2.3.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jaxb-core-2.3.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jaxb-runtime-2.3.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jna-4.4.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\jsonic-1.2.11.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\language-detector-0.6.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\language-fr-4.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\languagetool-core-4.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\lucene-backward-codecs-5.5.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\lucene-core-5.5.4.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\morfologik-fsa-2.1.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\morfologik-fsa-builders-2.1.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\morfologik-speller-2.1.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\morfologik-stemming-2.1.5.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\segment-2.0.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\slf4j-api-1.7.25.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\stax-ex-1.7.8.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\txw2-2.3.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\unit-api-1.0.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\uom-lib-common-1.1.jar.dir:C:\Users\Maxime\AppData\Local\Temp\tmplewadpgu\xgboost-predictor-0.3.0.jar.dir\ module-info.class
Loading class module-info and dependencies

Assertion failed!

Program: C:\Users\Maxime\Documents\writecontrol\LanguageTool-WebAssembly\cheerpj_1.3\bin\cheerpj

File: ClassFile.h, Line 213

Expression: false
`

Is there a tool to understand the runtime exception ? (Stack trace)

Could you give me information about the compilation problem.

**Comment by alexp-sssup** [comment]
I suspect that the library is trying to load binary (x86) component (libhunspell), CheerpJ cannot support this use case obviously.

**Comment by maxiplay** [comment]
Yes that's it.
But is there a solution to build a custom hunspell for CheerpJ using Cheerp for C++ ?

**Comment by alexp-sssup** [comment]
There is no out-of-the-box solution, with some amount of work you may make it work though. I am closing this bug since this is not truly a CheerpJ issue.

**Comment by maxiplay** [comment]
Ok thx for response !
