### ISSUE TITLE
ReferenceError: a is not defined

### ISSUE THREAD

**Issue by BillMoninger** [leaningtech/cheerpj-meta#59]
I used cheerpjfy.py on a jar file (world_15.jar) and got no error when it created world_15.jar.js -- using version 1.3 of cheerpj.

I then tried to use cheerpj to run my applet, and get the error below.

The page I'm trying to run is https://amdar.noaa.gov/demo_java/cheerpj_1.3/cheerpj.html.

This applet runs (nearly) correctly using the cheerpj app for chrome. You can see this behavior at
https://amdar.noaa.gov/demo_java/. (And you can see the totally correct behavior if you run the java web start version at https://amdar.noaa.gov/demo_java/GSD.AMDAR.jnlp.)

I'll be very grateful for any help you can provide.

ReferenceError: a is not defined[Learn More] world_15.jar.js:358:21998
Reporting error: ReferenceError: a is not defined/_c4VaMV9Grp7eqaYcYewnTeW0lWtAeHKx9n@https://amdar.noaa.gov/demo_java/cheerpj_1.3/world_15.jar.js:358:21998
_c4VaMx9Grp7eqaYcYewDndYfsJXkb9mSxno@https://amdar.noaa.gov/demo_java/cheerpj_1.3/world_15.jar.js:358:23500
_c4VaM39Grp7eqaYcYewT9dqKaXs7bXeGNxTo@https://amdar.noaa.gov/demo_java/cheerpj_1.3/world_15.jar.js:358:23952
_c4VaMJ8GrnoRdvdbZynhqtfGuD9IdWWFavrbrKxDn@https://amdar.noaa.gov/demo_java/cheerpj_1.3/world_15.jar.js:341:11454
anonymous@https://cjrtnc.leaningtech.com/1.3/loader.js line 116 > Function:3:350
runContinuationStack@https://cjrtnc.leaningtech.com/1.3/loader.js:383:8
cheerpjSchedule@https://cjrtnc.leaningtech.com/1.3/loader.js:1052:5

**Comment by BillMoninger** [comment]
The issue I reported was in Firefox. In Chrome, once I cleared the cache, the site now works! However it has the problem with TextArea.append that I reported for the CheerpJ applet runner that is now fixed in v7.0 of the applet runner. Is there a new version of the AOT compiler corresponding to AppletRunner v7.0?

Also (perhaps this should be a separate bug) is there any way I can make the text windows that can be called up (such as by right-clicking one of the data points) copy-able with cntl-c? (For the java text windows this can be done in windows, but not under iOS.)

**Comment by BillMoninger** [comment]
I spoke too soon. It only works intermittently in Chrome. I again cleared the cache and restarted Chrome and got the same (or similar) error:
Uncaught ReferenceError: a is not defined
    at _c4VaMV9Grp7eqaYcYewnTeW0lWtAeHKx9n (world_16.jar.js:358)
    at _c4VaMx9Grp7eqaYcYewDndYfsJXkb9mSxno (world_16.jar.js:358)
    at _c4VaM39Grp7eqaYcYewT9dqKaXs7bXeGNxTo (world_16.jar.js:358)
    at N3sdg14SoundingCanvas._c4VaMJ8GrnoRdvdbZynhqtfGuD9IdWWFavrbrKxDn [as v349] (world_16.jar.js:341)
    at Object.eval [as func] (eval at buildContinuations (loader.js:116), <anonymous>:3:352)
    at runContinuationStack (loader.js:383)
    at MessagePort.cheerpjSchedule (loader.js:1052)

**Comment by alexp-sssup** [comment]
The main error you reported ```a is not defined``` is now fixed in our master branch.

Unfortunately you will need to wait until the release of CheerpJ 1.4 to get this fix, as we can only provide nightly builds to commercial customers.
