### ISSUE TITLE
Secure random in Cheerpj

### ISSUE THREAD

**Issue by sergeypayu** [leaningtech/cheerpj-meta#61]
I can not find this information in your FAQ yet it's important for our application (we use cheerpj to run a java crypto library). How do you get random bytes in JS when java app is using SecureRandom class? Correct way to do it would be using Web Crypto API - https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues

[Why is Math.random() not designed to be cryptographically secure?](https://security.stackexchange.com/questions/181580/why-is-math-random-not-designed-to-be-cryptographically-secure)

**Comment by nanaian** [comment]
You can expose `Crypto.getRandomValues` through JNI methods. For example, with CheerpJ 3:

```java
package web;

public class Crypto {
  public static native int getRandomValue();
}
```

```js
await cheerpjInit({
  natives: {
    async Java_web_Crypto_getRandomValue(lib) {
      const array = new Uint32Array(1);
      crypto.getRandomValues(array);
      return array[0];
    },
  },
});
```

Documentation:
- [CheerpJ 3](https://labs.leaningtech.com/cheerpj3/guides/Implementing-Java-native-methods-in-JavaScript)
- [CheerpJ 2](https://labs.leaningtech.com/cheerpj2/guides/Implementing-Java-native-methods-in-JavaScript)

**Comment by sergeypayu** [comment]
Oh, wow, 4 and half years later :smiling_face_with_tear: I'm not sure that it's correct way to deal with the problem. If I run our java crypto lib on CheerpJ, it will would work but with a major hidden problem. SecureRandom should be internally implemented inside CheerpJ using secure methods. It should not create a major gotcha and security flow by default.

**Comment by nanaian** [comment]
Sorry, I misunderstood your issue - yes, you're correct, we should be using crypto internally! I'll reopen this.

**Comment by alexp-sssup** [comment]
Random data is now correctly sourced using WebCrypto
