### ISSUE TITLE
NullPointerException when accessing non-null string

### ISSUE THREAD

**Issue by joehitt** [leaningtech/cheerpj-meta#63]
We are seeing a particular String that comes back from CheerpJ transpiled Java code that throws a NullPointerException whenever the string is accessed.
 
For example this code:
```
         String s = fields[i].m_fieldName;
         if (s == null) {
            System.out.println("fields[i].m_fieldName was null!");
         } else {
            System.out.println("fields[i].m_fieldName was NOT null!");
            byte[] bytes = s.getBytes(StandardCharsets.UTF_8);   // NPE thrown here on getBytes when running transpiled
```
** However note that 'fields' comes back from our transpiled code, and unfortunately the codebase is proprietary and too large to post here (and requires too much context) so we are trying to pair that down to a minimal, reproducible test case and have not been able to do that just yet.  Just wanted to get an issue posted here in case there were ideas of how to troubleshoot it further as we continue to collect information.

What we see is that the NPE is thrown when s.getBytes() is accessed.  NullPointerException is also gets thrown when we try to print the string itself, or calling other methods on java.lang.String.
 
When running in Java (no transpilation), the string value is: “SURVEY_VETS100A”, and the sequence of UTF-8 bytes listed in decimal are:
83/85/82/86/69/89/95/86/69/84/83/49/48/48/65
 
...so I don’t think there is anything unusual about the underlying String data itself (no extended-byte characters, etc - pretty much just ASCII subset characters).
 
I also attempted returning this string up to the JavaScript level (as a Promise<string>) to see if we can see the string’s value.  When doing this, in the calling JavaScript code it resolves to _undefined_.  It seems maybe there is some underlying shim code internal to the CheerpJ port of java.lang.String that has some issue internally.
 
We are using the standard command to transpile and including log4j:
`cheerpjfy.py --deps=log4j-1.2.16.jar --pack-jar=Base.jar Base.jar`

**Comment by alexp-sssup** [comment]
The problem is that the String is (erroneously) the JS value ```undefined```, which is not ```null```, so nowithstanding the check ```if (s == null)``` an NPE will still be raised later on.

I don't know what the issue might be, but you should investigate on the _source_ of this ```undefined``` value (i.e. What API call generates this value?). Since the value is not a actually a valid String every use of that will crash as you observe.

**Comment by joehitt** [comment]
Thanks Alessandro, I suspected that this String exists as undefined within the underlying transpiled code as well.

However, per the API question, the value comes from transpiled Java code that made a remote HTTP request and got the String from de-serializing that request, so not sure how it had the opportunity to become undefined.  The serialization/deserialization is using the java mechanism based on java.io.Serializable so I wonder if there is something related to the transpiled deserialization framework.

So you have given me some good ideas - I think my next step is to try to grab the precise HTTP streamed data  using a proxy and see if I can produce a paired-down example that deserializes that object from a text file and reproduces the problem.  Just to note, the serialized class has a serializedVersionUID = 1L .

**Comment by joehitt** [comment]
Got some time to look into this one and it turned out that the String does not come from network/deserializaiton but rather evaluated from an instance passed in.  I was passing the wrong type into the transpiled function.  For example we have com.myinternalpackage.MyClass and I was passing an instance of com.myexternalpackage.MyClass (different package, same class name) which has a slightly different 'shape'.  I needed to instead call the cjNew function for the correct type and initialize it correctly.

While the behavior of java String having internal 'undefined' JS value is maybe not ideal (?), it was certainly not a CheerpJ bug.

Just thinking out loud here - it might be a 'nice to have' if the transpiler could optionally drop in some runtime type checking, maybe something like a 'dev mode' that could weave in some ability to ensure that 'undefined' doesn't end up in the java objects creating unpredictable results.  Also, as others have requested source-maps could be a really great thing for this project.

But in any case, this was problem caused by garbage-in, so closing...

Thanks!
