### ISSUE TITLE
Error when adding to String

### ISSUE THREAD

**Issue by samlalani** [leaningtech/cheerpj-meta#65]
CheerpJ 1.3
JDK 11.0.2
NetBeans 11

I created a small test Java application with a JFrame that allows the user to enter two numbers and then click "Add" or "Multiply" to get the answer.  However, I am seeing the following output when running cheerpjfy.py on my jar file:

	Compiling jar  TestMath.jar
	compiling testmath/Main.class ...
	compiling testmath/TestFrame.class ...
	Failure compiling testmath/TestFrame.class
	command: C:\Sam\cheerpj_1.3\bin\cheerpj "" -llvm -llvm-exceptions -cp C:\Users\samla\AppData\Local\Temp\tmpqm3a1k3z\rt.jar.dir\ testmath/TestFrame.class
	Loading class testmath/TestFrame and dependencies
	Could not open class java/lang/invoke/StringConcatFactory
	Unsupported LLVM generation for opcode ba
	In function main
	Unsupported LLVM generation for opcode ba
	In function c
	SUPPORT CONSTANT 8Assertion failed!
	
	Program: C:\Sam\cheerpj_1.3\bin\cheerpj
	File: CheerpJCompilerMethod.cpp, Line 2241
	
	Expression: false

The relevant snippet of code is:

            int answer = x + y;
            answer_TextField.setText ("" + answer);
            //answer_TextField.setText ("Sum");

That code gives me the error, but if I comment out the 2nd line and uncomment the third line then it works fine.  Please let me know how to fix it.  Thanks.

**Comment by alexp-sssup** [comment]
(I've closed the duplicate report on the other issue)

You need to compile the code using JDK8. CheerpJ does not yet support  other versions of Java.

**Comment by samlalani** [comment]
Compiling with JDK8 fixed it!  I assume JDK12 using WebAssembly is on a long-term plan.  Looking forward to that version.  Thanks, Alex :)
