### ISSUE TITLE
ReferenceError: _c4pbAW8oHWcYJeXTK1Kcnoq0GATnkB9niX0lrKeItJ3fS3n_o is not defined

### ISSUE THREAD

**Issue by WDZCJ** [leaningtech/cheerpj-meta#66]
hi,my java project depended on SWT. 
To run my project, it need 4 file like below
![image](https://user-images.githubusercontent.com/38930007/56187895-954fce00-6056-11e9-908c-700fc214be04.png)
When i convert my procject to Js, is ok.
error heepend when i open it by browser, error info shown below
![image](https://user-images.githubusercontent.com/38930007/56200343-2e8bde00-6071-11e9-9332-17c8c6d9819a.png)
looking for help ,thanks

**Comment by alexp-sssup** [comment]
SWT is a native toolkit, and as such it cannot run using CheerpJ. We may at some point in the future provide a Web port of SWT but that's a very significant project.

**Comment by WDZCJ** [comment]
Understood,thanks.
