### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by yuripourre** [leaningtech/cheerpj-meta#7]
Hello,

I am trying to use CheerpJ following the [Getting Started](https://github.com/leaningtech/cheerpj-meta/wiki/Getting-Started) Tutorial.

I am generating the jar using IntelliJ, I can perfectly run the jar via command line using `java -jar myjar.jar`

But for some reason I can't run using CheerpJ, I always get: *Could not find or load main class AppClass*

P.S.: I am using my own class name instead of AppClass.

**Comment by reportmill** [comment]
Can you post your HTML?

Also, you might want to post future dev questions to the cheerpj dev group: https://groups.google.com/forum/#!forum/cheerpj-developers

jeff

**Comment by yuripourre** [comment]
Sure.

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>CheerpJ test</title>
    <script src="https://cjrtnc.leaningtech.com/loader.js"></script>
  </head>
  <body>
  </body>
  <script>
      cheerpjInit();
      cheerpjCreateDisplay(800,600);
      cheerpjRunMain("InterpolationExample", "/app/etyl-examples.jar");
  </script>
</html>
```

CheerpJ can find the jar, and my class in the default package (root of jar). I can send the jar (and/or the .js) if needed.

**Comment by alexp-sssup** [comment]
Please send the JAR, the js is not needed.

**Comment by sergeypayu** [comment]
I have the same issue. Everything was fine until Beta 2 was released. After release I have "Could not find or load main class" error even though I recomplied jar file. In network profiler I also see that cheerpOS.js stopped to load compiled js file, now it only tries to load .jar file.

**Comment by sergeypayu** [comment]
OK, It was my mistake - the jar file actually wasn't accessible and my web server was returning redirect instead of file. So I think at this point I will convert my bug report into feature request - handle situation when jar file can't be loaded and report corresponding error message.

**Comment by yuripourre** [comment]
@alexp-sssup This is the jar I am trying to run using cheerpj: [link](https://github.com/Harium/etyl-examples/releases/download/cheerpj/etyl-examples.jar)

This is a big one-jar (1MB) with all dependencies and I copy the class InterpolationExample to the jar's root.

**Comment by yuripourre** [comment]
*Update:* Using Firefox, I got the error.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://docs.google.com/forms/d/e/1FAIpQLScErDRKZvSy1JAdiRSZfAsjf711VWdSdkczuSYHfIHQbtyFXA/formResponse. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by alexp-sssup** [comment]
I can confirm that the JAR works perfectly for me, 2 things to check

*) Can you try again with the web server root in the same directory as the HTML/JAR file?
*) Also post the JAR.JS files

**Comment by yuripourre** [comment]
@alexp-sssup Thank your for your help.

- I am already serving both the html and the jar in the web server's root. I can create a repository with the (Java) server if it helps.
- The jar.js file: [etyl-examples.jar.js.txt](https://github.com/leaningtech/cheerpj-meta/files/1401851/etyl-examples.jar.js.txt) (renamed to .txt to upload it here)

The .jar.js was generated using *python 3.5.2* in *Fedora 25*.

**Comment by alexp-sssup** [comment]
@yuripourre Everything works fine both on Chrome and Firefox for me, using the provided JAR and JAR.js files. I have used ```python -m SimpleHTTPServer``` started in the same directory containing the HTML/JAR/JAR.JS files for this test. Can you try with the same setup? Also feel free to share a repo as you suggested before.

**Comment by reportmill** [comment]
I was able to get it to run as well, however, I did have to modify your HTML to include the crossorigin attribute:

	From: <script src="https://cjrtnc.leaningtech.com/loader.js"></script>

	To: <script src="https://cjrtnc.leaningtech.com/loader.js" crossorigin="anonymous"></script>

jeff

**Comment by yuripourre** [comment]
I can run!

The problem was with my server (I have no idea why), I tried with a [simple http server in python](http://2ality.com/2014/06/simple-http-server.html) and it worked.

If I may suggest, a simple python server snippet could be included to the [Getting Started](https://github.com/leaningtech/cheerpj-meta/wiki/Getting-Started) Tutorial.

Thank you

```
#!/usr/bin/python

import SimpleHTTPServer
import SocketServer

PORT = 8000

Handler = SimpleHTTPServer.SimpleHTTPRequestHandler
Handler.extensions_map.update({
    '.webapp': 'application/x-web-app-manifest+json',
});

httpd = SocketServer.TCPServer(("", PORT), Handler)

print "Serving at port", PORT
httpd.serve_forever()
```

**Comment by alexp-sssup** [comment]
@yuripourre we know that CheerpJ is working fine with many different servers, can you give us more information on your specific server setup?

**Comment by yuripourre** [comment]
Sure, I am using a simple [sparkjava](http://sparkjava.com/) server to serve the files.

I am trying to figure out the problem.

**Comment by alexp-sssup** [comment]
@yuripourre As CheerpJ uses standard Web API to load all data and code you can use the network tab of the in-browser debugger to inspect what's different in the various scenarios.

**Comment by yuripourre** [comment]
I got something: When cheerpJ calls HEAD etyl-examples.jar, the python server responds with content-length.

But in sparkjava (over Jetty) the content-length is missing, maybe related to [this issue](https://dev.eclipse.org/mhonarc/lists/jetty-users/msg05330.html).

I will investigate it deeper later.

**Comment by alexp-sssup** [comment]
A correct content-length is required, the HEAD request is used to check for file existence and size at the same time.

**Comment by yuripourre** [comment]
That was the problem.
@alexp-sssup, @reportmill I solved this serving the files and forcing the server to put the content-length on responses.

Thank you again.
