### ISSUE TITLE
Uncaught ReferenceError: TL is not defined

### ISSUE THREAD

**Issue by conradkirschner** [leaningtech/cheerpj-meta#71]
loader.js:397 Uncaught ReferenceError: TL is not defined
    at _Java_java_util_zip_ZipFile_open (icu.js:1)
    at cheerpjJNILongRetWrapper (loader.js:1998)
    at _i4pbNs9DgYZ$mYZhYcbUZdrJNTo (rt.jar.js:1672)
    at _i4pbNc9DgYZ$mYZhYcbNTho (rt.jar.js:1679)
    at _i4pbNc9DgYZ$mYZhYcbNTNn (rt.jar.js:1679)
    at _i4pbNsajmVpce9HSqWz7Hd (rt.jar.js:1513)
    at _i4pbNsajmVpce9HSqWz7rd (rt.jar.js:1513)
    at _c4FbMlG9cq$a_sCunE5rj4DiXYdruDVbXKjasd3cGK0xKdZiqKxnp (rt.jar.js:1706)
    at _c4FbMlG9cq$a_sCunE5rjSDiXYdruTUWbHGIwZqPdWGjasJNnn (rt.jar.js:1706)
    at Object.func

Edit: Reason was a wrong path in       
cheerpjRunJar("/app/*.jar");

**Comment by alexp-sssup** [comment]
Can you share with us the code or a link where we can test this? I suspect that CheerpJ is not being initialized correctly, that error is usually caused by a JAR/zip file not being downloaded correctly.

**Comment by conradkirschner** [comment]
yes i had it in a sub folder... localhost/applet/Bezier.jar ... moved it to localhost directly to quick fix that ... 
sorry my fault ... 

now I have this ... 

CheerpJ is initializing
cheerpOS.js:1400 no main manifest attribute, in /app/Bezier.jar
cheerpOS.js:1400 

loader.js:2106 Unhandled exception N4java4lang20NullPointerException /
loader.js:443 Uncaught (in promise)

**Comment by alexp-sssup** [comment]
You said that this was an applet right? How are you starting it using CheerpJ? Does the original Web page work with our CheerpJ Applet Runner extension? https://chrome.google.com/webstore/detail/cheerpj-applet-runner/bbmolahhldcbngedljfadjlognfaaein

**Comment by conradkirschner** [comment]
yes it does ... thats why i was thinking the porting should be possible ...

**Comment by conradkirschner** [comment]
<APPLET CODEBASE="./java" ARCHIVE="Bezier.jar" CODE="Bezier.class" WIDTH="541" HEIGHT="402" ALIGN="BOTTOM">
      </APPLET>
this is how it is included into the page ....

**Comment by alexp-sssup** [comment]
Ok, if it works with CheerpJ Applet Runner then you only need to call ```cheerpjInit()``` in the page and the system will take care of everything.

I think you are trying to use ```cheerpjRunMain``` or ```cheerpjRunJar``` which cannot be used on applet, those are for Java applications.

See here for more info: https://github.com/leaningtech/cheerpj-meta/wiki/Getting-started

**Comment by conradkirschner** [comment]
super great support & work! 

where is your "Buy me a Coffee" link or your donate link, I would like to say thank you... <3

**Comment by alexp-sssup** [comment]
We would appreciate a 5-star review for our extension: https://chrome.google.com/webstore/detail/cheerpj-applet-runner/bbmolahhldcbngedljfadjlognfaaein

If you can talk or tweet about our tech that's also welcome. Have a nice day.
