### ISSUE TITLE
Import concurrent.futures

### ISSUE THREAD

**Issue by stevepamel** [leaningtech/cheerpj-meta#72]
Tried to run a basic test and received the following error message:
c:\cheerpj_1.4>cheerpjfy.py Test.jar
Traceback (most recent call last):
  File "C:\cheerpj_1.4\cheerpjfy.py", line 13, in <module>
    import concurrent.futures
ImportError: No module named concurrent.futures

**Comment by alexp-sssup** [comment]
You need to use Python 3 to run cheerpjfy.py
