### ISSUE TITLE
The getting started tutorial does not work in Win 10 Pro. None of the .exec files in /cheerp_bl/bin can run.

### ISSUE THREAD

**Issue by PhuongNQK** [leaningtech/cheerpj-meta#73]

**Comment by alexp-sssup** [comment]
What version of CheerpJ are you using? What is the exact error message you
see? In the past we had issues with Antivirus softwares that would
mistakenly flag our programs as malicious (they are not, obviously); so
make sure that this isn't an Antivirus issue.

**Comment by alexp-sssup** [comment]
Closing due to lack of details.
