### ISSUE TITLE
After Downloading how to install Cheerpj , Can anyone help me with Step by Step procedure. Thanks in Advance.

### ISSUE THREAD

**Issue by ruthwickbabu** [leaningtech/cheerpj-meta#74]

**Comment by alexp-sssup** [comment]
Are you using the version for Windows, MacOS or Linux?

**Comment by ruthwickbabu** [comment]
> Are you using the version for Windows, MacOS or Linux?

Windows 10

**Comment by alexp-sssup** [comment]
CheerpJ is distributed in a ZIP archive, you have downloaded a file called cheerpj_win_1.4.zip. You can simply unzip the whole package anywhere in your hard drive, for example in your Documents folder

**Comment by ruthwickbabu** [comment]
> CheerpJ is distributed in a ZIP archive, you have downloaded a file called cheerpj_win_1.4.zip. You can simply unzip the whole package anywhere in your hard drive, for example in your Documents folder. There is not real installation step, just unzip.

Yes, I unzipped in Downloads, there are bin, cheerbl , cheerpj-dom , cheerpj-PY, cheerpj-public, LISCENCE-md, rt. I opened cheerbl->tools->msdbuild->Install, But its not happening.

**Comment by alexp-sssup** [comment]
After unzipping you are done, there is nothing else to do. You can immediately use the cheerpjfy.py script to conver JARs to JAR.JS from the command line. Please see: https://github.com/leaningtech/cheerpj-meta/wiki/Getting-started (in particular the "Note to Windows users" paragraph).

**Comment by ruthwickbabu** [comment]
> cheerpjfy.py

How to do that please

**Comment by alexp-sssup** [comment]
Make sure to have python 3 installed. Then opend the windows cmd (command line interface/terminal) and try the following command.

```
py c:\Users\UserName\Downloads\cheerpj_1.4\cheerpjfy.py application.jar
```

**Comment by ruthwickbabu** [comment]
> Make sure to have python 3 installed. Then opend the windows cmd (command line interface/terminal) and try the following command.
> 
> ```

Is there any possible way to do without any Phython 3 .
> py c:\Users\UserName\Downloads\cheerpj_1.4\cheerpjfy.py application.jar
> ```

Can I do with

**Comment by alexp-sssup** [comment]
No, you need python 3.

**Comment by ruthwickbabu** [comment]
> No, you need python 3.

Thanks for the help and Information
