### ISSUE TITLE
Name mangling for native methods...

### ISSUE THREAD

**Issue by smduarte** [leaningtech/cheerpj-meta#77]
Hi,

Except for name mangling, native methods provide a nice, almost transparent, way to interface compiled Java with JavaScript or other languages that compile to JavaScript, such as Dart...

I wish we could supply the desired JS name for a native method, for instance via a Java Annotation.

**Comment by alexp-sssup** [comment]
CheerpJ has integrated support for automatically generating stubs for each native method in a JAR. This makes it possible to mostly ignore name mangling, as CheerpJ will generate all the proper signature by itself. See here for more info: https://github.com/leaningtech/cheerpj-meta/wiki/Command-Line-Options#--stub-nativesnativespath

From within the generate code you can then easily forward to any other JS code, or directly implement the methods.

Is this solution sufficient for your use case?

**Comment by alexp-sssup** [comment]
**Note**: Due a build system misconfiguration a required helper executable for ```--stub-natives=``` was missing in the CheerpJ 2.0 packages. This problem has been fixed, make sure to download the 2.0 packages from scratch before trying this functionality.

**Comment by smduarte** [comment]
Hi,

Thank you for your reply.

The stubs generated for the native methods do make more sense after the update, but does not address my issue.

I wanted a seamless way for java code to call an existing javascript library. For instance
by defining a Java class or interface whose methods map directly to javascript code
that already exists, like you provide for accessing the DOM. This way, Java could
take advantage of the myriad of high quality JS libraries we have in the wild.

The native methods approach would fit the bill if we could have a way to control of the name of the javascript method that was bound to each java method, for instance via an annotation. Dart does this.

As it is, the other alternative I see is to define a Java interface with default methods (or class) and
call Javascript explicitly via Global.jsCall, but I'd expect this will introduce some un-necessary overhead...
 
Anyway, thank you for a great product. I was completely blown away when I converted 
my application and it ran perfectly in the browser.

**Comment by alexp-sssup** [comment]
Thanks for your kind words. In the future we plan to expand the functionality of our DOM access system to allow using arbitrary libraries.

In the mean time I could suggest to use the ```--stub-natives``` features plus some custom scripting to automatically create the wrappers you need. How does this sound?

**Comment by smduarte** [comment]
Hi,

I will look forward to the new functionality.

In the mean time, I will manage with what you already provide.

Again, thank you for an awesome product.

Best Regards,

Sérgio

**Comment by alexp-sssup** [comment]
Access to natives has been completely redesigned as part of the new CheerpJ 3.0 architecture. We believe the new feature set solves the issues raised here.

For more info: https://labs.leaningtech.com/cheerpj3/guides/Implementing-Java-native-methods-in-JavaScript

**Comment by Akiva-Cohen** [comment]
> Access to natives has been completely redesigned as part of the new CheerpJ 3.0 architecture. We believe the new feature set solves the issues raised here.
> 
> For more info: https://labs.leaningtech.com/cheerpj3/guides/Implementing-Java-native-methods-in-JavaScript

is it possible to use this with a .jar or do you need to do it with a .class
If it is with a .jar how do you do name mangling
I did it and it is leading to the "cheerpj is initializing" page to load infinitlely

**Comment by alexp-sssup** [comment]
> is it possible to use this with a .jar or do you need to do it with a .class

Natives works the same way independently of the origin of classes. Name mangling is always connected to a class since each native method is contained in a class.

For further support please consider joining our Discord: https://discord.leaningtech.com

**Comment by Akiva-Cohen** [comment]
> > is it possible to use this with a .jar or do you need to do it with a .class
> 
> Natives works the same way independently of the origin of classes. Name mangling is always connected to a class since each native method is contained in a class.
> 
> For further support please consider joining our Discord: https://discord.leaningtech.com

thanks i was not expecting anyone to answer a 5 year old thread
it turns out the problem was with my schools network connection so it works now
