### ISSUE TITLE
Dragging of window titlebar

### ISSUE THREAD

**Issue by sebhaase** [leaningtech/cheerpj-meta#79]
This is a followup to issue #78.  As you suggested, resizing the window - by dragging the bottom right corner of the window - is working.  Is moving the window by dragging the title-bar supposed to work?
It behaves like an HTML `<img>` where `dragging=false` was forgotten to set.
Apparently the code of the title bar is `<div class="titleBar" draggable="true">`  - but you cannot drag the window, or am I missing something...?

**Comment by alexp-sssup** [comment]
Dragging the windows is supported, but currently works best in Chrome. Firefox is known to be working but it's a bit glitchy. What browser are you using?

**Comment by sebhaase** [comment]
I tried Chrome on Windows and Chrome on OSX. Neither is working for me.

**Comment by alexp-sssup** [comment]
Can you share a test case with us, including the HTML code? Also try the Swing example on our fiddle: https://javafiddle.leaningtech.com/

**Comment by sebhaase** [comment]
Apparently it does work if I open the html file directly - I was using it inside `<embed>`. It even works if I change that to a normal `<iframe>`.
Sorry for the noise...
Now I would like to ask if I can simulate the dragging from "outside" Javascript. (and the resizing) - which kind of events would that be: mousedown, mousemove etc. ?
(should I open a new issue?)

**Comment by alexp-sssup** [comment]
The system currently uses the 'drag' family of events over the titleBar element. Although you can try to simulate the right events to get the windows behaviour you want, you should be aware that these are consider an internal interface and may change at any time. I apologize for these limitations, but as usual, we are a small company so we need to carefully prioritize the features we implement.

**Comment by alexp-sssup** [comment]
Dragging of the titlebar with the mouse has been supported for a long time, simulate dragging via an API is outside the scope of the project. Closing.
