### ISSUE TITLE
'Undefied' error when trying to make a sync method call

### ISSUE THREAD

**Issue by sergeypayu** [leaningtech/cheerpj-meta#8]
If I try to execute method in a sync way using cjCallSync I get 'cjForceSync is not defined' error. I guess you either need to make cjForceSync global or remove line "assert(!cjForceSync);" in loader.js

**Comment by alexp-sssup** [comment]
cjCallSync it's an internal API and should not be used

**Comment by sergeypayu** [comment]
Ok, I'm I right that cjCall  is a public method and cjCallSync is not?

**Comment by alexp-sssup** [comment]
Yes, that's correct.

**Comment by sergeypayu** [comment]
Ok, then as a suggestion, it's better to hide the function from deployment code or make it really working. I do miss ability to call some function in a sync way.
