### ISSUE TITLE
legacy codegen: FATAL: kernel too old

### ISSUE THREAD

**Issue by BillMoninger** [leaningtech/cheerpj-meta#83]
I just downloaded cheerpj_2.1. When I run 
cheerpjfy.py <my jar file> 
I get a huge number of errors (one for each class file in the jar, I presume) like this:

Using legacy codegen for sdg/SoundingLoader.class
FATAL: kernel too old
compiling sdg/SoundingPanel.class ...
FATAL: kernel too old
Failure compiling sdg/SoundingPanel.class
command: /w3/emb/amdar/demo_java/cheerpj_2.1/bin/cheerpj "" -llvm -llvm-exceptions -cp /tmp/tmp3i48pdhd/rt.jar.dir/ sdg/SoundingPanel.class

I recompiled all the java files into class files today, so I doubt that my class files are too old.

Any ideas?

**Comment by alexp-sssup** [comment]
Can you try with a more recent version of Linux or either the MacOS or Windows build of CheerpJ.

**Comment by alexp-sssup** [comment]
I could confirm that CheerpJ 2.1 works with Linux kernels as old as 3.13 released in 2014, corresponding to Ubuntu LTS Trusty. I am not sure how much before CheerpJ will run, but it's likely that you are currently using an obsolete version of Linux. Please update your system and try again, closing this bug.
