### ISSUE TITLE
The entire app crashes after java.awt.Window.dispose is called

### ISSUE THREAD

**Issue by oeway** [leaningtech/cheerpj-meta#90]
I think this maybe a but in cheerpj, see the error below:
```
Exception in thread "AWT-EventQueue-0" 
cheerpOS.js:1491 java.lang.NullPointerException
cheerpOS.js:1491 

cheerpOS.js:1491 	at com.leaningtech.cheerpj.CheerpJFramePeer.setMenuBar(Unknown Source)
cheerpOS.js:1491 

cheerpOS.js:1491 	at java.awt.Frame.removeNotify(Unknown Source)
cheerpOS.js:1491 

cheerpOS.js:1491 	at java.awt.Window$1DisposeAction.run(Unknown Source)
cheerpOS.js:1491 

cheerpOS.js:1491 	at java.awt.Window.doDispose(Unknown Source)
cheerpOS.js:1491 

cheerpOS.js:1491 	at java.awt.Window.dispose(Unknown Source)
```

**Comment by carlopi** [comment]
Can you share with us the jar + html source so we can reproduce / investigate the problem?

**Comment by oeway** [comment]
Yes, definitely. I am compiling an image processing software named "ImageJ", hosted here: https://ij.imjoy.io/. All my source code is here: https://github.com/imjoy-team/imagej.js

The jar file is in [this zip](https://github.com/imjoy-team/imagej.js/releases/download/0.1.x/ij153.zip), named "ij.jar". And the compiled html is in the gh-pages branch of the repo, but I made a minimal version for your investigation [here](https://gist.github.com/oeway/5e3e6cc131de732d1caa913cc91580d5).

To reproduce the issue, click in the menu "Plugins > New > Macro"
<img width="399" alt="Screenshot 2020-08-29 at 20 55 58" src="https://user-images.githubusercontent.com/478667/91644181-11736780-ea3a-11ea-8f09-95b68c1f25c8.png">
In the opened text editor window, type anything then close the window, it ask you whether you want to save it, click "Don't save", the entire app hangs. 

If I edit the java code, and remove the `dispose()` call [here](https://github.com/imagej/imagej1/blob/ffa061fd53e4c0a6cde89840a64079589ea7fd43/ij/plugin/frame/Editor.java#L1149), then it works. 

You can also see all the java code which we used to get the ij.jar file. If you have `ant` installed, you can do:
```
git clone https://github.com/imagej/imagej1
cd imagej1
ant build
# now you should get a file named "ij.jar"
${CHEERP}/cheerpjfy.py ij.jar
```
Hope this will help, and please let me know if you need more information.

**Comment by angilbert** [comment]
I have seen this exact same crash when disposing of an AWT Frame (owned by an applet object). Removing the dispose() call helped in the first instance, but if I subsequently created a new Frame and then assigned it the same MenuBar then there is a later crash. I suspect the MenuBar object is being freed with the Frame it was originally assigned to even though it is a separate object (created before the Frame object). You can work-around the issue by not disposing of the original Frame but keeping a reference to it for later re-use, if this is practical.

**Comment by oeway** [comment]
Thanks for the suggestion @angilbert , I removed the dispose call and it works for me for now.

**Comment by alexp-sssup** [comment]
This problem is fixed with the new endpoint: https://cjrtnc.leaningtech.com/20200906/loader.js

**Comment by oeway** [comment]
I confirm it works now with the latest version, thanks a lot! @alexp-sssup
