### ISSUE TITLE
First byte missing when passing from js to java

### ISSUE THREAD

**Issue by oeway** [leaningtech/cheerpj-meta#91]
Hi, I am encountering a wired bug when I try to pass a `Int8Array` from javascript to call a function in Java (via `cjResolveCall`), but on the Java side, the byte array I got does not contain the first byte.

In java define:
```java
public static void saveBytes(byte[] bytes, String path) {
    System.out.println("1st:"+bytes[0]+", 2nd:"+bytes[1]);
}
```

In Javascript:
```js
const saveBytes = await cjResolveCall("org.MyClass", "saveBytes", null)

const bytesIn = new Int8Array(new ArrayBuffer(30));
bytesIn[0] = 33;
bytesIn[2] = 99;
await saveBytes(bytesIn, "");
```

After running this, the actual console output is:
```
1st:0, 2nd:99
```
The expected output should be `1st:33, 2nd:0`.

(I am using `2.1/loader.js`)

**Comment by carlopi** [comment]
I think for this you should call (on the JavaScript side) cjTypedArrayToJava for converting your Int8Array into a type compatible with byte[].
See in particular this paragraph from our wiki: https://github.com/leaningtech/cheerpj-meta/wiki/Runtime-API#cjtypedarraytojava

**Comment by oeway** [comment]
Thanks for the response! Indeed, by adding `cjTypedArrayToJava` it worked, sorry that I missed that part and I assumes the conversion is automatic.

However, do we have a function to convert from java to js typed array? I am now returning a bytes[] from java to js, and I got a `Int8Array` with an additional first byte `66`.

**Comment by carlopi** [comment]
In loader.js there is defined a function called cjTypedArrayToJava, that basically takes care of encoding the type of an array as 0-th element, then copying element N in position N+1.

An inverse function (from array+type to JavaScript array) is not available (yet!), but you could write one dropping the first element and mapping N+1 into N.
This if you know at compile time the type that would be returned, but if you want a general solution, you could also check the value of the first element, and from there select what kind of array to generate.

**Comment by oeway** [comment]
Thanks for the detailed explanation! OK, I will do that for now.
I am doing a lot of hacking in my version and hope some of them can be addressed in your future release. 

BTW, would you mind if I create more related issues I found on github or do you prefer I do it in gitter?

**Comment by carlopi** [comment]
It's great to hear about current limits, the priorities this bugs/improvements will receive will vary but eventually they will all be addressed.

I think the policy is:
-opening an issue here if you think you have found a bug of some kind
-asking on Gitter or [stackoverflow](https://stackoverflow.com/questions/ask?tags=cheerpj) for question about things that might be potentially answered by other users / if you are looking for a solution (but it's not a bug).

Then the lines are blurry, since it's not always clear in advance, so do whatever seems right.

**Comment by oeway** [comment]
Thanks @carlopi !

Close this issue now.

**Comment by oeway** [comment]
@carlopi Do you have a table of data type encoding? E.g. {66: "Uint8Array", 73: "..", ...} I would like to make a complete implementation of `javaBytesToArrayBuffer()`.

**Comment by alexp-sssup** [comment]
@oeway You should be able to use the information in cjTypedArrayToJava. Please understand that using the first element to encode the type is an implementation detail and may change in future versions of CheerpJ.
