### ISSUE TITLE
java.awt.CheckboxMenuItem is not clickable

### ISSUE THREAD

**Issue by oeway** [leaningtech/cheerpj-meta#93]
This is likely a bug, I cannot click any checkbox menu item (regular menu item works). [This](https://github.com/imjoy-team/ImageJA/blob/767b61d8720567b44303b327fb7deb0b2f564342/src/main/java/ij/Menus.java#L157-L165) is the java code adds them.
Hope this can be fixed, I will have to replace them into regular menu item for now.

**Comment by alexp-sssup** [comment]
Checkboxs are now displayed correctly and are clickable with endpoint: https://cjrtnc.leaningtech.com/20200907/loader.js

**Comment by oeway** [comment]
@alexp-sssup Thanks for fixing this. 

However, it  doesn't seem to work for me.

I changed back in my jar file to use checkbokMenuItem, and used the latest above. If you go to https://ij.imjoy.io (reload once), open an image and click "Image -> Type -> 16bit" for example, nothing happened, and also the display seems wrong. Did I miss anything?

<img width="573" alt="Screenshot 2020-09-07 at 21 07 27" src="https://user-images.githubusercontent.com/478667/92412934-28a70900-f14e-11ea-854e-ab696c2f968f.png">

**Comment by alexp-sssup** [comment]
Make sure that custom page code is not altering the generated menu elements. In particular the ```fixMenus``` function looks suspicious.

**Comment by oeway** [comment]
> Make sure that custom page code is not altering the generated menu elements. In particular the `fixMenus` function looks suspicious.

I afraid no, `fixMenus` only remove certain items.

I found something wired, some checkboxMenuItem actually works:
<img width="471" alt="Screenshot 2020-09-07 at 23 28 02" src="https://user-images.githubusercontent.com/478667/92417345-f3a4b180-f161-11ea-9b19-a3dbbbcd842d.png">

The one works are generated by the code [here](https://github.com/imjoy-team/ImageJA.JS/blob/ba55a70c1c1ab77f8582a5f0f1e55fdeac7395bb/src/main/java/ij/Menus.java#L1373-L1380), in the same file, all the ones generated from [another function](https://github.com/imjoy-team/ImageJA.JS/blob/ba55a70c1c1ab77f8582a5f0f1e55fdeac7395bb/src/main/java/ij/Menus.java#L451-L459) doesn't work.

**Comment by alexp-sssup** [comment]
I can confirm 100% that ```fixMenu``` is causing the problem. The line ```it.text = it.text.trim();``` will erase the elements contained in the menu item.

**Comment by oeway** [comment]
You are right!!! Just tired and it works! I am so sorry.

**Comment by oeway** [comment]
The new menu looks awesome BTW, thank you again for the fix!
