### ISSUE TITLE
Rewriter error in the buildContinuations function

### ISSUE THREAD

**Issue by oeway** [leaningtech/cheerpj-meta#95]
I encountered a potential bug, when I am running a function the `buildContinuations` function rasie the following error and the entire app hangs:
```
loader.js:115 Uncaught SyntaxError: Unexpected token ')'
    at new Function (<anonymous>)
    at buildContinuations (loader.js:115)
    at buildContinuations (loader.js:111)
    at buildContinuations (loader.js:111)
    at buildContinuations (loader.js:111)
    at buildContinuations (loader.js:111)
    at buildContinuations (loader.js:111)
    at buildContinuations (loader.js:111)
    at buildContinuations (loader.js:111)
    at buildContinuations (loader.js:111)
```
I digged a bit into the error, `caller.name` is `_c4_07Filters22Enhance_Leq2Z_Contrast3runE2`,  the rewrittencaller is a string: `var label=0;var p=a.p;var l0=a.l0;var l1=a.l1;var l2=a.l2;var l3=a.l3;var l4=a.l4;var s0=a.s0;var s1=a.s1;;)V').i)(a.s0,a);a.s0=a.l2;a.pc=90;a.s0.v15(a.s0,a);return;}else{a.pc=74;a.s0=a.l2;a.pc=75;a.s0.v15(a.s0,a);return;}` which contains indeed syntax error with a half `)` bracket. 

Here is [the java source](https://github.com/imjoy-team/imagej.js/blob/gh-pages/ij153/plugins/Filters/Enhance_Local_Contrast.java), [the class file](https://github.com/imjoy-team/imagej.js/blob/gh-pages/ij153/plugins/Filters/Enhance_Local_Contrast.class) and [ the compiled .js](https://github.com/imjoy-team/imagej.js/blob/gh-pages/ij153/plugins/Filters/Enhance_Local_Contrast.js).

The loader I am using is https://cjrtnc.leaningtech.com/2.1/loader.js

To reproduce, you can also go to http://ij.imjoy.io/, click "File -> Open Samples -> AuPbSn 40", then click "Plugins -> Filters -> Enhance Local Contrast", you will see a popup dialog, click ok then you will see the error in the console.

**Comment by carlopi** [comment]
I do reproduce the problem, we will investigate and get back.

Very nice the progress you made, now you can load sample images / do transformations.

**Comment by oeway** [comment]
Thank you @carlopi Yes, I get the hang of calling between JS and Java, that allows me fixing the socket based downloading with javascript and trigger dialog from JS. 

Most of the features for ImageJ.JS are there, there are a few things I would like to fix before the release. I will make separate issue for it.

**Comment by alexp-sssup** [comment]
This issue is fixed with the endpoint: https://cjrtnc.leaningtech.com/20200906_3/loader.js

**Comment by oeway** [comment]
Awesome! Just tried it and works as expected!

Huge thanks to you @alexp-sssup !
