### ISSUE TITLE
Support removing files mounted to /str

### ISSUE THREAD

**Issue by oeway** [leaningtech/cheerpj-meta#97]
Would be nice to support removing files mounted to /str, to lower the memory footprint. I made a function for that for ImageJ.JS: 
```js
function cheerpjRemoveStringFile(name) {
  var mount = cheerpjGetFSMountForPath(name);
  assert(mount instanceof CheerpJDataFolder);
  delete mount.files[name.substr(mount.mountPoint.length - 1)]
  delete cjFileCache[name];
}
```
Maybe something like this should be integrated to or provided from the official loader?

**Comment by alexp-sssup** [comment]
cheerpjRemoveStringFile is implemented in endpoint https://cjrtnc.leaningtech.com/20201217/loader.js
